import type { Maybe } from '../maybe.js';
import type { WhoId } from '../dialogueEngine/enums/who.js';
import type { EnvId } from '../dialogueEngine/enums/env.js';
import type { NumberVariableId, BooleanVariableId } from '../dialogueEngine/enums/variable.js';

export type ScriptKind = 'ai' | 'cutscene';

export type ObjectQuery = Readonly<{
  ea?: Maybe<string>;
  faction?: Maybe<string>;
  team?: Maybe<string>;
  general?: Maybe<string>;
  race?: Maybe<string>;
  class?: Maybe<string>;
  specific?: Maybe<string>;
  gender?: Maybe<string>;
  align?: Maybe<string>;
}>;

export type ScriptTarget = WhoId | ObjectQuery | string;

export type ScriptAction = (l: ScriptLogic) => void;
export type ScriptCondition = (l: ScriptLogic, ctx: Readonly<{ myself: WhoId | string }>) => boolean;

export type ScriptResponse = Readonly<{
  weight: number;
  whoId: WhoId | string;
  continue: boolean;
  actions: readonly ScriptAction[];
}>;

export type ScriptBlock = Readonly<{
  condition: ScriptCondition;
  responses: readonly ScriptResponse[];
}>;

export type ScriptDefinition = Readonly<{
  kind: ScriptKind;
  resourceName: string;
  blocks: readonly ScriptBlock[];
}>;

/** Stub surface for BCS ghost. Shell implements later. */
export type ScriptLogic = Readonly<{
  actionOverride: (target: ScriptTarget, action: () => void) => void;
  triggerOverride: (target: ScriptTarget, test: () => boolean) => boolean;
  setValue: (args: Readonly<{ variableId: NumberVariableId | BooleanVariableId | string; envId?: Maybe<EnvId | string>; amount: number }>) => number;
  getValue: (args: Readonly<{ variableId: NumberVariableId | BooleanVariableId | string; envId?: Maybe<EnvId | string> }>) => number;
  getValueEq: (args: Readonly<{ variableId: NumberVariableId | BooleanVariableId | string; envId?: Maybe<EnvId | string>; amount: number }>) => boolean;
  getValueGt: (args: Readonly<{ variableId: NumberVariableId | BooleanVariableId | string; envId?: Maybe<EnvId | string>; amount: number }>) => boolean;
  getValueLt: (args: Readonly<{ variableId: NumberVariableId | BooleanVariableId | string; envId?: Maybe<EnvId | string>; amount: number }>) => boolean;
  increment: (args: Readonly<{ variableId: NumberVariableId | string; envId?: Maybe<EnvId | string>; amount: number }>) => number;
  wait: (seconds: number) => void;
  endCutsceneMode: () => void;
  faceObject: (args: Readonly<{ whoId: WhoId | string; to: WhoId | string }>) => void;
  dialogue: (whoId: WhoId | string) => void;
  actionlistempty: (...args: readonly unknown[]) => boolean;
  activate: (...args: readonly unknown[]) => void;
  addexperienceparty: (...args: readonly unknown[]) => void;
  addglobals: (...args: readonly unknown[]) => void;
  alignment: (...args: readonly unknown[]) => boolean;
  allegiance: (...args: readonly unknown[]) => boolean;
  applydamage: (...args: readonly unknown[]) => void;
  applyspellres: (...args: readonly unknown[]) => void;
  areacheck: (...args: readonly unknown[]) => boolean;
  attack: (...args: readonly unknown[]) => void;
  attackedBy: (...args: readonly unknown[]) => boolean;
  bitcheck: (...args: readonly unknown[]) => boolean;
  bitclear: (...args: readonly unknown[]) => void;
  bitset: (...args: readonly unknown[]) => void;
  changeAiScript: (...args: readonly unknown[]) => void;
  changeAlignment: (...args: readonly unknown[]) => void;
  changeColor: (...args: readonly unknown[]) => void;
  changeDialog: (...args: readonly unknown[]) => void;
  changeEnemyAlly: (...args: readonly unknown[]) => void;
  changeSpecifics: (...args: readonly unknown[]) => void;
  changeTeam: (...args: readonly unknown[]) => void;
  checkspellstate: (...args: readonly unknown[]) => boolean;
  checkstatgt: (...args: readonly unknown[]) => boolean;
  checkstatlt: (...args: readonly unknown[]) => boolean;
  class: (...args: readonly unknown[]) => boolean;
  classlevelgt: (...args: readonly unknown[]) => boolean;
  classlevellt: (...args: readonly unknown[]) => boolean;
  clearactions: (...args: readonly unknown[]) => void;
  clearallactions: (...args: readonly unknown[]) => void;
  clicked: (...args: readonly unknown[]) => boolean;
  closedoor: (...args: readonly unknown[]) => void;
  createCreature: (...args: readonly unknown[]) => void;
  createcreatureimpassable: (...args: readonly unknown[]) => void;
  createitem: (...args: readonly unknown[]) => void;
  createvisualeffect: (...args: readonly unknown[]) => void;
  damage: (...args: readonly unknown[]) => void;
  deactivate: (...args: readonly unknown[]) => void;
  dead: (...args: readonly unknown[]) => boolean;
  destroypartyitem: (...args: readonly unknown[]) => void;
  destroyself: (...args: readonly unknown[]) => void;
  die: (...args: readonly unknown[]) => boolean;
  died: (...args: readonly unknown[]) => boolean;
  difficultygt: (...args: readonly unknown[]) => boolean;
  difficultylt: (...args: readonly unknown[]) => boolean;
  disablefogdither: (...args: readonly unknown[]) => void;
  disablespritedither: (...args: readonly unknown[]) => void;
  displaystringhead: (...args: readonly unknown[]) => void;
  dropinventory: (...args: readonly unknown[]) => void;
  enablefogdither: (...args: readonly unknown[]) => void;
  enablespritedither: (...args: readonly unknown[]) => void;
  enemy: (...args: readonly unknown[]) => void;
  entered: (...args: readonly unknown[]) => boolean;
  equipmostdamagingmelee: (...args: readonly unknown[]) => void;
  escapeareamove: (...args: readonly unknown[]) => void;
  exists: (...args: readonly unknown[]) => boolean;
  explore: (...args: readonly unknown[]) => void;
  exploremapchunk: (...args: readonly unknown[]) => void;
  face: (...args: readonly unknown[]) => void;
  faction: (...args: readonly unknown[]) => boolean;
  fadefromcolor: (...args: readonly unknown[]) => void;
  fadetocolor: (...args: readonly unknown[]) => void;
  failedtoopen: (...args: readonly unknown[]) => boolean;
  false: (...args: readonly unknown[]) => boolean;
  floatMessage: (...args: readonly unknown[]) => void;
  floatMessageFixed: (...args: readonly unknown[]) => void;
  floatMessageRnd: (...args: readonly unknown[]) => void;
  forceaiscript: (...args: readonly unknown[]) => void;
  forcefacing: (...args: readonly unknown[]) => void;
  forcespellres: (...args: readonly unknown[]) => void;
  forcespellresnofeedback: (...args: readonly unknown[]) => void;
  generatepartymember: (...args: readonly unknown[]) => void;
  giveitemcreate: (...args: readonly unknown[]) => void;
  globalTimerExpired: (...args: readonly unknown[]) => boolean;
  globalTimerNotexpired: (...args: readonly unknown[]) => boolean;
  harmlessclosed: (...args: readonly unknown[]) => boolean;
  harmlessentered: (...args: readonly unknown[]) => boolean;
  harmlessopened: (...args: readonly unknown[]) => boolean;
  hasitem: (...args: readonly unknown[]) => boolean;
  haveanyspells: (...args: readonly unknown[]) => boolean;
  havespell: (...args: readonly unknown[]) => boolean;
  heard: (...args: readonly unknown[]) => boolean;
  help: (...args: readonly unknown[]) => void;
  hitby: (...args: readonly unknown[]) => boolean;
  hpLt: (...args: readonly unknown[]) => boolean;
  hpPercentLt: (...args: readonly unknown[]) => boolean;
  inCrementglobalonce: (...args: readonly unknown[]) => void;
  inParty: (...args: readonly unknown[]) => boolean;
  inTeractingwith: (...args: readonly unknown[]) => boolean;
  isactive: (...args: readonly unknown[]) => boolean;
  islocked: (...args: readonly unknown[]) => boolean;
  isoverme: (...args: readonly unknown[]) => boolean;
  joinparty: (...args: readonly unknown[]) => void;
  jumptopoint: (...args: readonly unknown[]) => void;
  kill: (...args: readonly unknown[]) => void;
  killfloatmessage: (...args: readonly unknown[]) => void;
  lastAttackerOf: (whoId: WhoId | string) => WhoId | string;
  leavearealua: (...args: readonly unknown[]) => void;
  leaveparty: (...args: readonly unknown[]) => void;
  los: (...args: readonly unknown[]) => boolean;
  moralelt: (...args: readonly unknown[]) => boolean;
  moraleset: (...args: readonly unknown[]) => void;
  mostDamagedOf: (whoId: WhoId | string) => WhoId | string;
  moveToObject: (...args: readonly unknown[]) => void;
  moveToObjectFollow: (...args: readonly unknown[]) => void;
  moveToPoint: (...args: readonly unknown[]) => void;
  moveToSavedLocationN: (...args: readonly unknown[]) => void;
  moveViewObject: (...args: readonly unknown[]) => void;
  moveViewPoint: (...args: readonly unknown[]) => void;
  name: (...args: readonly unknown[]) => boolean;
  namelessbitthedust: (...args: readonly unknown[]) => boolean;
  nearByDialog: (...args: readonly unknown[]) => boolean;
  nearestEnemyOf: (whoId: WhoId | string) => WhoId | string;
  nearLocation: (...args: readonly unknown[]) => boolean;
  nearSavedLocation: (...args: readonly unknown[]) => boolean;
  nearSavedLocationPst: (...args: readonly unknown[]) => boolean;
  noaction: (...args: readonly unknown[]) => void;
  notstatecheck: (...args: readonly unknown[]) => boolean;
  nulldialog: (...args: readonly unknown[]) => boolean;
  numberoftimestalkedto: (...args: readonly unknown[]) => boolean;
  numcreature: (...args: readonly unknown[]) => boolean;
  numcreaturegt: (...args: readonly unknown[]) => boolean;
  numcreaturelt: (...args: readonly unknown[]) => boolean;
  numinpartygt: (...args: readonly unknown[]) => boolean;
  numinpartylt: (...args: readonly unknown[]) => boolean;
  numtimestalkedtogt: (...args: readonly unknown[]) => boolean;
  onCreation: (...args: readonly unknown[]) => boolean;
  opendoor: (...args: readonly unknown[]) => void;
  opened: (...args: readonly unknown[]) => boolean;
  openstate: (...args: readonly unknown[]) => boolean;
  partyHasitem: (...args: readonly unknown[]) => boolean;
  partyScriptSactive: (...args: readonly unknown[]) => boolean;
  picklockfailed: (...args: readonly unknown[]) => boolean;
  pickpocketfailed: (...args: readonly unknown[]) => boolean;
  playDead: (...args: readonly unknown[]) => void;
  playSequence: (...args: readonly unknown[]) => void;
  playSequenceTimed: (...args: readonly unknown[]) => void;
  playSong: (...args: readonly unknown[]) => void;
  playSound: (...args: readonly unknown[]) => void;
  playSoundnotranged: (...args: readonly unknown[]) => void;
  playSoundthroughvoice: (...args: readonly unknown[]) => void;
  polymorph: (...args: readonly unknown[]) => void;
  protectobject: (...args: readonly unknown[]) => void;
  quitgame: (...args: readonly unknown[]) => void;
  race: (...args: readonly unknown[]) => boolean;
  randomFace: (...args: readonly unknown[]) => void;
  randomNum: (...args: readonly unknown[]) => boolean;
  randomNumlt: (...args: readonly unknown[]) => boolean;
  randomWalk: (...args: readonly unknown[]) => void;
  range: (...args: readonly unknown[]) => boolean;
  reallyforcespellres: (...args: readonly unknown[]) => void;
  receivedorder: (...args: readonly unknown[]) => boolean;
  resToRezoomlevel: (...args: readonly unknown[]) => void;
  returnToSavedPlace: (...args: readonly unknown[]) => void;
  runAwayFrom: (...args: readonly unknown[]) => void;
  runningattack: (...args: readonly unknown[]) => void;
  runtoobject: (...args: readonly unknown[]) => void;
  runtopoint: (...args: readonly unknown[]) => void;
  runtosavedplace: (...args: readonly unknown[]) => void;
  saveobjectlocation: (...args: readonly unknown[]) => void;
  saveplace: (...args: readonly unknown[]) => void;
  see: (...args: readonly unknown[]) => boolean;
  sendtrigger: (...args: readonly unknown[]) => void;
  setanimstate: (...args: readonly unknown[]) => void;
  setcorpseenabled: (...args: readonly unknown[]) => void;
  setdialog: (...args: readonly unknown[]) => void;
  setdoorlocked: (...args: readonly unknown[]) => void;
  setglobaltimer: (...args: readonly unknown[]) => void;
  setglobaltimerrandom: (...args: readonly unknown[]) => void;
  setinterrupt: (...args: readonly unknown[]) => void;
  setnooneontrigger: (...args: readonly unknown[]) => void;
  setportalcursor: (...args: readonly unknown[]) => void;
  setrenderable: (...args: readonly unknown[]) => void;
  setsequence: (...args: readonly unknown[]) => void;
  setzoomviewport: (...args: readonly unknown[]) => void;
  shout: (...args: readonly unknown[]) => void;
  sinisterpoof: (...args: readonly unknown[]) => void;
  smallwait: (...args: readonly unknown[]) => void;
  specifics: (...args: readonly unknown[]) => boolean;
  spellpointres: (...args: readonly unknown[]) => void;
  spellRes: (...args: readonly unknown[]) => void;
  startCutscene: (...args: readonly unknown[]) => void;
  startCutsceneMode: (...args: readonly unknown[]) => void;
  startCutscenepst: (...args: readonly unknown[]) => void;
  startDialog: (...args: readonly unknown[]) => void;
  startDialogUenoset: (...args: readonly unknown[]) => void;
  startMovie: (...args: readonly unknown[]) => void;
  startRandomTimer: (...args: readonly unknown[]) => void;
  startTimer: (...args: readonly unknown[]) => void;
  statecheck: (...args: readonly unknown[]) => boolean;
  staticsequence: (...args: readonly unknown[]) => void;
  staticstart: (...args: readonly unknown[]) => void;
  staticstop: (...args: readonly unknown[]) => void;
  stealfailed: (...args: readonly unknown[]) => boolean;
  stickysinisterpoof: (...args: readonly unknown[]) => void;
  storezoomlevel: (...args: readonly unknown[]) => void;
  team: (...args: readonly unknown[]) => boolean;
  teleportparty: (...args: readonly unknown[]) => void;
  timedmovetopoint: (...args: readonly unknown[]) => void;
  timegt: (...args: readonly unknown[]) => boolean;
  timelt: (...args: readonly unknown[]) => boolean;
  timeofday: (...args: readonly unknown[]) => boolean;
  timerActive: (...args: readonly unknown[]) => boolean;
  timerExpired: (...args: readonly unknown[]) => boolean;
  trigger: (...args: readonly unknown[]) => boolean;
  triggeractivation: (...args: readonly unknown[]) => void;
  undoexplore: (...args: readonly unknown[]) => void;
  unlocked: (...args: readonly unknown[]) => boolean;
  vacant: (...args: readonly unknown[]) => boolean;
  verbalconstant: (...args: readonly unknown[]) => void;
  waitForvoicechannel: (...args: readonly unknown[]) => void;
  waitRandom: (...args: readonly unknown[]) => void;
  waitSync: (...args: readonly unknown[]) => void;
  wasInDialog: (...args: readonly unknown[]) => boolean;
}>;

export type ScriptSkeleton = (l: ScriptLogic, ctx: Readonly<{ myself: WhoId | string }>) => ScriptDefinition;

