import createWriter from '@/shared/writer.js';
import { escapeSingleQuote } from '@/steps/5.json2Ghost/shared.js';

import type { GhostCreatureV10, GhostCreatureV11 } from '../../../types.js';

type GhostCreature = GhostCreatureV10 | GhostCreatureV11;

const createNpcLowercaseId = (resourceName: string): string => {
  const candidate = resourceName.split('.')[0]!.replace(`'`, ``);
  // @ts-expect-error : js is a meme, but efficient meme
  const isDigit = candidate[0] > -1;
  if (isDigit) return `_${candidate}`;
  return candidate;
};

const translateCreature = (cre: GhostCreature): string => {
  const npcLowercaseId = createNpcLowercaseId(cre.resourceName);

  const writer = createWriter();
  writer.writeLine(`import type { UntranslatedCreature, TranslatedCreature } from '@planar/shared';`);
  writer.br();
  writer.writeLine('/**');
  writer.writeLine(` * Original source: ${cre.resourceName}`);
  writer.writeLine(' */');
  writer.writeLine(`const ${npcLowercaseId}Creature = (${npcLowercaseId}CreatureSkeleton: UntranslatedCreature): TranslatedCreature => {`);
  writer.writeLine(`return {`, 2);
  writer.writeLine(`...${npcLowercaseId}CreatureSkeleton,`, 4);
  writer.writeLine(`nameTlk: '${escapeSingleQuote(cre.header.nameTlk)}',`, 4);
  writer.writeLine(`tooltipTlk: '${escapeSingleQuote(cre.header.tooltipTlk)}',`, 4);
  writer.writeLine(`initialMeetingSoundTlk: '${escapeSingleQuote(cre.header.initialMeetingSoundTlk)}',`, 4);
  writer.writeLine(`moraleSoundTlk: '${escapeSingleQuote(cre.header.moraleSoundTlk)}',`, 4);
  writer.writeLine(`happySoundTlk: '${escapeSingleQuote(cre.header.happySoundTlk)}',`, 4);
  writer.writeLine(`unhappyAnnoyedSoundTlk: '${escapeSingleQuote(cre.header.unhappyAnnoyedSoundTlk)}',`, 4);
  writer.writeLine(`unhappySeriousSoundTlk: '${escapeSingleQuote(cre.header.unhappySeriousSoundTlk)}',`, 4);
  writer.writeLine(`unhappyBreakingPointSoundTlk: '${escapeSingleQuote(cre.header.unhappyBreakingPointSoundTlk)}',`, 4);
  writer.writeLine(`leaderSoundTlk: '${escapeSingleQuote(cre.header.leaderSoundTlk)}',`, 4);
  writer.writeLine(`tiredSoundTlk: '${escapeSingleQuote(cre.header.tiredSoundTlk)}',`, 4);
  writer.writeLine(`boredSoundTlk: '${escapeSingleQuote(cre.header.boredSoundTlk)}',`, 4);
  writer.writeLine(`battleCry1SoundTlk: '${escapeSingleQuote(cre.header.battleCry1SoundTlk)}',`, 4);
  writer.writeLine(`battleCry2SoundTlk: '${escapeSingleQuote(cre.header.battleCry2SoundTlk)}',`, 4);
  writer.writeLine(`battleCry3SoundTlk: '${escapeSingleQuote(cre.header.battleCry3SoundTlk)}',`, 4);
  writer.writeLine(`battleCry4SoundTlk: '${escapeSingleQuote(cre.header.battleCry4SoundTlk)}',`, 4);
  writer.writeLine(`battleCry5SoundTlk: '${escapeSingleQuote(cre.header.battleCry5SoundTlk)}',`, 4);
  writer.writeLine(`attack1SoundTlk: '${escapeSingleQuote(cre.header.attack1SoundTlk)}',`, 4);
  writer.writeLine(`attack2SoundTlk: '${escapeSingleQuote(cre.header.attack2SoundTlk)}',`, 4);
  writer.writeLine(`attack3SoundTlk: '${escapeSingleQuote(cre.header.attack3SoundTlk)}',`, 4);
  writer.writeLine(`attack4SoundTlk: '${escapeSingleQuote(cre.header.attack4SoundTlk)}',`, 4);
  writer.writeLine(`damageSoundTlk: '${escapeSingleQuote(cre.header.damageSoundTlk)}',`, 4);
  writer.writeLine(`dyingSoundTlk: '${escapeSingleQuote(cre.header.dyingSoundTlk)}',`, 4);
  writer.writeLine(`hurtSoundTlk: '${escapeSingleQuote(cre.header.hurtSoundTlk)}',`, 4);
  writer.writeLine(`areaForestSoundTlk: '${escapeSingleQuote(cre.header.areaForestSoundTlk)}',`, 4);
  writer.writeLine(`areaCitySoundTlk: '${escapeSingleQuote(cre.header.areaCitySoundTlk)}',`, 4);
  writer.writeLine(`areaDungeonSoundTlk: '${escapeSingleQuote(cre.header.areaDungeonSoundTlk)}',`, 4);
  writer.writeLine(`areaDaySoundTlk: '${escapeSingleQuote(cre.header.areaDaySoundTlk)}',`, 4);
  writer.writeLine(`areaNightSoundTlk: '${escapeSingleQuote(cre.header.areaNightSoundTlk)}',`, 4);
  writer.writeLine(`selectCommon1SoundTlk: '${escapeSingleQuote(cre.header.selectCommon1SoundTlk)}',`, 4);
  writer.writeLine(`selectCommon2SoundTlk: '${escapeSingleQuote(cre.header.selectCommon2SoundTlk)}',`, 4);
  writer.writeLine(`selectCommon3SoundTlk: '${escapeSingleQuote(cre.header.selectCommon3SoundTlk)}',`, 4);
  writer.writeLine(`selectCommon4SoundTlk: '${escapeSingleQuote(cre.header.selectCommon4SoundTlk)}',`, 4);
  writer.writeLine(`selectCommon5SoundTlk: '${escapeSingleQuote(cre.header.selectCommon5SoundTlk)}',`, 4);
  writer.writeLine(`selectCommon6SoundTlk: '${escapeSingleQuote(cre.header.selectCommon6SoundTlk)}',`, 4);
  writer.writeLine(`selectAction1SoundTlk: '${escapeSingleQuote(cre.header.selectAction1SoundTlk)}',`, 4);
  writer.writeLine(`selectAction2SoundTlk: '${escapeSingleQuote(cre.header.selectAction2SoundTlk)}',`, 4);
  writer.writeLine(`selectAction3SoundTlk: '${escapeSingleQuote(cre.header.selectAction3SoundTlk)}',`, 4);
  writer.writeLine(`selectAction4SoundTlk: '${escapeSingleQuote(cre.header.selectAction4SoundTlk)}',`, 4);
  writer.writeLine(`selectAction5SoundTlk: '${escapeSingleQuote(cre.header.selectAction5SoundTlk)}',`, 4);
  writer.writeLine(`selectAction6SoundTlk: '${escapeSingleQuote(cre.header.selectAction6SoundTlk)}',`, 4);
  writer.writeLine(`selectAction7SoundTlk: '${escapeSingleQuote(cre.header.selectAction7SoundTlk)}',`, 4);
  writer.writeLine(`interaction1SoundTlk: '${escapeSingleQuote(cre.header.interaction1SoundTlk)}',`, 4);
  writer.writeLine(`interaction2SoundTlk: '${escapeSingleQuote(cre.header.interaction2SoundTlk)}',`, 4);
  writer.writeLine(`interaction3SoundTlk: '${escapeSingleQuote(cre.header.interaction3SoundTlk)}',`, 4);
  writer.writeLine(`interaction4SoundTlk: '${escapeSingleQuote(cre.header.interaction4SoundTlk)}',`, 4);
  writer.writeLine(`interaction5SoundTlk: '${escapeSingleQuote(cre.header.interaction5SoundTlk)}',`, 4);
  writer.writeLine(`insult1SoundTlk: '${escapeSingleQuote(cre.header.insult1SoundTlk)}',`, 4);
  writer.writeLine(`insult2SoundTlk: '${escapeSingleQuote(cre.header.insult2SoundTlk)}',`, 4);
  writer.writeLine(`insult3SoundTlk: '${escapeSingleQuote(cre.header.insult3SoundTlk)}',`, 4);
  writer.writeLine(`compliment1SoundTlk: '${escapeSingleQuote(cre.header.compliment1SoundTlk)}',`, 4);
  writer.writeLine(`compliment2SoundTlk: '${escapeSingleQuote(cre.header.compliment2SoundTlk)}',`, 4);
  writer.writeLine(`compliment3SoundTlk: '${escapeSingleQuote(cre.header.compliment3SoundTlk)}',`, 4);
  writer.writeLine(`special1SoundTlk: '${escapeSingleQuote(cre.header.special1SoundTlk)}',`, 4);
  writer.writeLine(`special2SoundTlk: '${escapeSingleQuote(cre.header.special2SoundTlk)}',`, 4);
  writer.writeLine(`special3SoundTlk: '${escapeSingleQuote(cre.header.special3SoundTlk)}',`, 4);
  writer.writeLine(`reactToDieGeneralSoundTlk: '${escapeSingleQuote(cre.header.reactToDieGeneralSoundTlk)}',`, 4);
  writer.writeLine(`reactToDieSpecificSoundTlk: '${escapeSingleQuote(cre.header.reactToDieSpecificSoundTlk)}',`, 4);
  writer.writeLine(`responseToCompliment1SoundTlk: '${escapeSingleQuote(cre.header.responseToCompliment1SoundTlk)}',`, 4);
  writer.writeLine(`responseToCompliment2SoundTlk: '${escapeSingleQuote(cre.header.responseToCompliment2SoundTlk)}',`, 4);
  writer.writeLine(`responseToCompliment3SoundTlk: '${escapeSingleQuote(cre.header.responseToCompliment3SoundTlk)}',`, 4);
  writer.writeLine(`responseToInsult1SoundTlk: '${escapeSingleQuote(cre.header.responseToInsult1SoundTlk)}',`, 4);
  writer.writeLine(`responseToInsult2SoundTlk: '${escapeSingleQuote(cre.header.responseToInsult2SoundTlk)}',`, 4);
  writer.writeLine(`responseToInsult3SoundTlk: '${escapeSingleQuote(cre.header.responseToInsult3SoundTlk)}',`, 4);
  writer.writeLine(`dialogHostileSoundTlk: '${escapeSingleQuote(cre.header.dialogHostileSoundTlk)}',`, 4);
  writer.writeLine(`dialogDefaultSoundTlk: '${escapeSingleQuote(cre.header.dialogDefaultSoundTlk)}',`, 4);
  writer.writeLine(`selectRare1SoundTlk: '${escapeSingleQuote(cre.header.selectRare1SoundTlk)}',`, 4);
  writer.writeLine(`selectRare2SoundTlk: '${escapeSingleQuote(cre.header.selectRare2SoundTlk)}',`, 4);
  writer.writeLine(`criticalHitSoundTlk: '${escapeSingleQuote(cre.header.criticalHitSoundTlk)}',`, 4);
  writer.writeLine(`criticalMissSoundTlk: '${escapeSingleQuote(cre.header.criticalMissSoundTlk)}',`, 4);
  writer.writeLine(`targetImmuneSoundTlk: '${escapeSingleQuote(cre.header.targetImmuneSoundTlk)}',`, 4);
  writer.writeLine(`inventoryFullSoundTlk: '${escapeSingleQuote(cre.header.inventoryFullSoundTlk)}',`, 4);
  writer.writeLine(`pickedPicketSoundTlk: '${escapeSingleQuote(cre.header.pickedPicketSoundTlk)}',`, 4);
  writer.writeLine(`hiddenInShadowsSoundTlk: '${escapeSingleQuote(cre.header.hiddenInShadowsSoundTlk)}',`, 4);
  writer.writeLine(`spellDisruptedSoundTlk: '${escapeSingleQuote(cre.header.spellDisruptedSoundTlk)}',`, 4);
  writer.writeLine(`setTrapSoundTlk: '${escapeSingleQuote(cre.header.setTrapSoundTlk)}',`, 4);
  writer.writeLine(`existance4SoundTlk: '${escapeSingleQuote(cre.header.existance4SoundTlk)}',`, 4);
  writer.writeLine(`bioSoundTlk: '${escapeSingleQuote(cre.header.bioSoundTlk)}',`, 4);
  writer.writeLine(`sound1Tlk: '${escapeSingleQuote(cre.header.sound1Tlk)}',`, 4);
  writer.writeLine(`sound2Tlk: '${escapeSingleQuote(cre.header.sound2Tlk)}',`, 4);
  writer.writeLine(`sound3Tlk: '${escapeSingleQuote(cre.header.sound3Tlk)}',`, 4);
  writer.writeLine(`sound4Tlk: '${escapeSingleQuote(cre.header.sound4Tlk)}',`, 4);
  writer.writeLine(`sound5Tlk: '${escapeSingleQuote(cre.header.sound5Tlk)}',`, 4);
  writer.writeLine(`sound6Tlk: '${escapeSingleQuote(cre.header.sound6Tlk)}',`, 4);
  writer.writeLine(`sound7Tlk: '${escapeSingleQuote(cre.header.sound7Tlk)}',`, 4);
  writer.writeLine(`sound8Tlk: '${escapeSingleQuote(cre.header.sound8Tlk)}',`, 4);
  writer.writeLine(`sound9Tlk: '${escapeSingleQuote(cre.header.sound9Tlk)}',`, 4);
  writer.writeLine(`sound10Tlk: '${escapeSingleQuote(cre.header.sound10Tlk)}',`, 4);
  writer.writeLine(`sound11Tlk: '${escapeSingleQuote(cre.header.sound11Tlk)}',`, 4);
  writer.writeLine(`sound12Tlk: '${escapeSingleQuote(cre.header.sound12Tlk)}',`, 4);
  writer.writeLine(`sound13Tlk: '${escapeSingleQuote(cre.header.sound13Tlk)}',`, 4);
  writer.writeLine(`sound14Tlk: '${escapeSingleQuote(cre.header.sound14Tlk)}',`, 4);
  writer.writeLine(`sound15Tlk: '${escapeSingleQuote(cre.header.sound15Tlk)}',`, 4);
  writer.writeLine(`sound16Tlk: '${escapeSingleQuote(cre.header.sound16Tlk)}',`, 4);
  writer.writeLine(`sound17Tlk: '${escapeSingleQuote(cre.header.sound17Tlk)}',`, 4);
  writer.writeLine(`sound18Tlk: '${escapeSingleQuote(cre.header.sound18Tlk)}',`, 4);
  writer.writeLine(`sound19Tlk: '${escapeSingleQuote(cre.header.sound19Tlk)}',`, 4);
  writer.writeLine(`sound20Tlk: '${escapeSingleQuote(cre.header.sound20Tlk)}',`, 4);
  writer.writeLine(`sound21Tlk: '${escapeSingleQuote(cre.header.sound21Tlk)}',`, 4);
  writer.writeLine(`sound22Tlk: '${escapeSingleQuote(cre.header.sound22Tlk)}',`, 4);
  writer.writeLine(`sound23Tlk: '${escapeSingleQuote(cre.header.sound23Tlk)}',`, 4);
  writer.writeLine(`sound24Tlk: '${escapeSingleQuote(cre.header.sound24Tlk)}',`, 4);
  writer.writeLine(`sound25Tlk: '${escapeSingleQuote(cre.header.sound25Tlk)}',`, 4);
  writer.writeLine(`};`, 2);
  writer.writeLine('};');
  writer.writeLine(`export default ${npcLowercaseId}Creature;`);

  return writer.done();
};

export default translateCreature;
