import type { Maybe } from '@planar/shared';

export type RawCreItemSlotsV11 = Readonly<{
  leftEarringOrLensOrHelmet: Maybe<number>;
  chest: Maybe<number>;
  rightLowerTattoo: Maybe<number>;
  hand: Maybe<number>;
  rightRing: Maybe<number>;
  leftRing: Maybe<number>;
  rightEarringOrEyeball: Maybe<number>;
  leftTattoo: Maybe<number>;
  wrist: Maybe<number>;
  weapon1: Maybe<number>;
  weapon2: Maybe<number>;
  weapon3: Maybe<number>;
  weapon4: Maybe<number>;
  quiver1: Maybe<number>;
  quiver2: Maybe<number>;
  quiver3: Maybe<number>;
  quiver4: Maybe<number>;
  rightUpperRattoo: Maybe<number>;
  quickItem1: Maybe<number>;
  quickItem2: Maybe<number>;
  quickItem3: Maybe<number>;
  inventoryItem1: Maybe<number>;
  inventoryItem2: Maybe<number>;
  inventoryItem3: Maybe<number>;
  inventoryItem4: Maybe<number>;
  inventoryItem5: Maybe<number>;
  inventoryItem6: Maybe<number>;
  inventoryItem7: Maybe<number>;
  inventoryItem8: Maybe<number>;
  inventoryItem9: Maybe<number>;
  inventoryItem10: Maybe<number>;
  inventoryItem11: Maybe<number>;
  inventoryItem12: Maybe<number>;
  inventoryItem13: Maybe<number>;
  inventoryItem14: Maybe<number>;
  inventoryItem15: Maybe<number>;
  inventoryItem16: Maybe<number>;
  magicWeapon: Maybe<number>;
  selectedWeapon: number;
  selectedWeaponAbility: number;
}>;
