import { isNothing } from '@planar/shared';

import type { RawAre } from '@/steps/4.biffs2json/pstee/are/parseAres.types.js';
import type { RawAreActorV10 } from '@/steps/4.biffs2json/pstee/are/v1.0/2.parseActors.types.js';
import type { RawAreRegionV10 } from '@/steps/4.biffs2json/pstee/are/v1.0/3.parseRegions.types.js';
import type { RawAreSpawnPointV10 } from '@/steps/4.biffs2json/pstee/are/v1.0/4.parseSpawnPoints.types.js';
import type { RawAreContainerV10 } from '@/steps/4.biffs2json/pstee/are/v1.0/6.parseContainers.types.js';
import type { RawAreAmbientV10 } from '@/steps/4.biffs2json/pstee/are/v1.0/9.parseAmbients.types.js';
import type { RawAreDoorV10 } from '@/steps/4.biffs2json/pstee/are/v1.0/12.parseDoors.types.js';
import type { RawAreAnimationV10 } from '@/steps/4.biffs2json/pstee/are/v1.0/13.parseAnimations.types.js';
import type { RawAreTiledObjectV10 } from '@/steps/4.biffs2json/pstee/are/v1.0/14.parseTiledObjects.types.js';
import type { RawAreRestInterruptionsV10 } from '@/steps/4.biffs2json/pstee/are/v1.0/18.parseRestInterruptions.types.js';
import type {
  GhostAre,
  GhostAreActor,
  GhostAreAmbient,
  GhostAreAnimation,
  GhostAreContainer,
  GhostAreDoor,
  GhostAreRegion,
  GhostAreRestInterruptions,
  GhostAreSpawnPoint,
  GhostAreTiledObject,
} from '@planar/shared';

const toActor = (actor: RawAreActorV10): GhostAreActor => ({
  name: actor.name,
  at: actor.at,
  destX: actor.destX,
  destY: actor.destY,
  flags: [...actor.flags],
  isSpawnedAsRandomMonster: actor.isSpawnedAsRandomMonster,
  creResrefLetter: actor.creResrefLetter,
  animation: actor.animation,
  direction: actor.direction,
  expiryTime: actor.expiryTime,
  wanderDistance: actor.wanderDistance,
  followDistance: actor.followDistance,
  presentedAt: [...actor.presentedAt],
  numTimesTalkedTo: actor.numTimesTalkedTo,
  dialog: actor.dialog,
  scriptOverride: actor.scriptOverride,
  scriptGeneral: actor.scriptGeneral,
  scriptClass: actor.scriptClass,
  scriptRace: actor.scriptRace,
  scriptDefault: actor.scriptDefault,
  scriptSpecifics: actor.scriptSpecifics,
  cre: actor.cre,
});

const toRegion = (region: RawAreRegionV10): GhostAreRegion => ({
  name: region.name,
  type: region.type,
  boundingBox: region.boundingBox,
  vertices: region.vertices.map(v => ({ x: v.x, y: v.y })),
  triggerValue: region.triggerValue,
  cursorIndex: region.cursorIndex,
  destinationArea: region.destinationArea,
  entranceName: region.entranceName,
  flags: [...region.flags],
  infoPointTextRef: region.infoPointTextRef,
  trapDetectionDifficulty: region.trapDetectionDifficulty,
  trapRemovalDifficulty: region.trapRemovalDifficulty,
  trapped: region.trapped,
  trapDetected: region.trapDetected,
  trapLaunchAt: region.trapLaunchAt,
  key: region.key,
  script: region.script,
  activation: region.activation,
  sound: region.sound,
  speaker: region.speaker,
  speakerNameRef: region.speakerNameRef,
  dialog: region.dialog,
});

const toSpawnPoint = (spawn: RawAreSpawnPointV10): GhostAreSpawnPoint => ({
  name: spawn.name,
  at: spawn.at,
  creatures: [...spawn.creatures],
  encounterDifficulty: spawn.encounterDifficulty,
  spawnRate: spawn.spawnRate,
  method: [...spawn.method],
  duration: spawn.duration,
  wanderDistance: spawn.wanderDistance,
  followDistance: spawn.followDistance,
  maxCreatures: spawn.maxCreatures,
  enabled: spawn.enabled,
  presentedAt: [...spawn.presentedAt],
  probabilityDay: spawn.probabilityDay,
  probabilityNight: spawn.probabilityNight,
  frequency: spawn.frequency,
  countdown: spawn.countdown,
  weights: [...spawn.weights],
});

const toContainer = (container: RawAreContainerV10): GhostAreContainer => ({
  name: container.name,
  at: container.at,
  type: container.type,
  lockDifficulty: container.lockDifficulty,
  flags: [...container.flags],
  trapDetectionDifficulty: container.trapDetectionDifficulty,
  trapRemovalDifficulty: container.trapRemovalDifficulty,
  trapped: container.trapped,
  trapDetected: container.trapDetected,
  launch: container.launch,
  boundingBox: container.boundingBox,
  items: container.items.map(item => ({
    resref: item.resref,
    expiryTime: item.expiryTime,
    quantity1: item.quantity1,
    quantity2: item.quantity2,
    quantity3: item.quantity3,
    flags: [...item.flags],
  })),
  trapScript: container.trapScript,
  vertices: container.vertices.map(v => ({ x: v.x, y: v.y })),
  triggerRange: container.triggerRange,
  owner: container.owner,
  key: container.key,
  breakDifficulty: container.breakDifficulty,
  lockpickStringRef: container.lockpickStringRef,
});

const toAmbient = (ambient: RawAreAmbientV10): GhostAreAmbient => ({
  name: ambient.name,
  at: ambient.at,
  radius: ambient.radius,
  height: ambient.height,
  pitchVariation: ambient.pitchVariation,
  volumeVariation: ambient.volumeVariation,
  volume: ambient.volume,
  sounds: [...ambient.sounds],
  intervalBase: ambient.intervalBase,
  intervalVariation: ambient.intervalVariation,
  presentedAt: [...ambient.presentedAt],
  flags: [...ambient.flags],
});

const toDoor = (door: RawAreDoorV10): GhostAreDoor => ({
  name: door.name,
  doorId: door.doorId,
  flags: [...door.flags],
  openedGeometry: {
    boundingBox: door.openedGeometry.boundingBox,
    vertices: door.openedGeometry.vertices.map(v => ({ x: v.x, y: v.y })),
    impeded: door.openedGeometry.impeded.map(v => ({ x: v.x, y: v.y })),
  },
  closedGeometry: {
    boundingBox: door.closedGeometry.boundingBox,
    vertices: door.closedGeometry.vertices.map(v => ({ x: v.x, y: v.y })),
    impeded: door.closedGeometry.impeded.map(v => ({ x: v.x, y: v.y })),
  },
  hitPoints: door.hitPoints,
  armorClass: door.armorClass,
  openSound: door.openSound,
  closeSound: door.closeSound,
  cursorIndex: door.cursorIndex,
  trapDetectionDifficulty: door.trapDetectionDifficulty,
  trapRemovalDifficulty: door.trapRemovalDifficulty,
  trapped: door.trapped,
  trapDetected: door.trapDetected,
  launch: door.launch,
  key: door.key,
  script: door.script,
  detectionDifficulty: door.detectionDifficulty,
  lockDifficulty: door.lockDifficulty,
  openLocation: door.openLocation,
  closeLocation: door.closeLocation,
  lockpickStringRef: door.lockpickStringRef,
  travelTriggerName: door.travelTriggerName,
  speakerNameRef: door.speakerNameRef,
  dialog: door.dialog,
});

const toAnimation = (animation: RawAreAnimationV10): GhostAreAnimation => ({
  name: animation.name,
  at: animation.at,
  presentedAt: [...animation.presentedAt],
  animationResref: animation.animationResref,
  bamSequenceNumber: animation.bamSequenceNumber,
  bamFrameNumber: animation.bamFrameNumber,
  flags: [...animation.flags],
  height: animation.height,
  transparency: animation.transparency,
  startFrame: animation.startFrame,
  loopProbability: animation.loopProbability,
  skipCycles: animation.skipCycles,
  palette: animation.palette,
  animationWidth: animation.animationWidth,
  animationHeight: animation.animationHeight,
});

const toTiledObject = (tiled: RawAreTiledObjectV10): GhostAreTiledObject => ({
  name: tiled.name,
  tileId: tiled.tileId,
  flags: [...tiled.flags],
  openImpeded: tiled.openImpeded.map(v => ({ x: v.x, y: v.y })),
  closedImpeded: tiled.closedImpeded.map(v => ({ x: v.x, y: v.y })),
});

const toRestInterruptions = (rest: RawAreRestInterruptionsV10): GhostAreRestInterruptions => ({
  name: rest.name,
  explanationRefs: [...rest.explanationRefs],
  creatures: [...rest.creatures],
  difficulty: rest.difficulty,
  removalTime: rest.removalTime,
  wanderDistance: rest.wanderDistance,
  followDistance: rest.followDistance,
  maxCreatures: rest.maxCreatures,
  enabled: rest.enabled,
  probabilityDay: rest.probabilityDay,
  probabilityNight: rest.probabilityNight,
});

export const toGhost = (raw: RawAre): GhostAre => ({
  resourceName: raw.resourceName,
  header: {
    signature: raw.header.signature,
    version: raw.header.version,
    wed: raw.header.wed,
    lastSaved: raw.header.lastSaved,
    flags: [...raw.header.flags],
    northAreaRef: raw.header.northAreaRef,
    northAreaFlags: [...raw.header.northAreaFlags],
    eastAreaRef: raw.header.eastAreaRef,
    eastAreaFlags: [...raw.header.eastAreaFlags],
    southAreaRef: raw.header.southAreaRef,
    southAreaFlags: [...raw.header.southAreaFlags],
    westAreaRef: raw.header.westAreaRef,
    westAreaFlags: [...raw.header.westAreaFlags],
    areaType: [...raw.header.areaType],
    rainProbability: raw.header.rainProbability,
    snowProbability: raw.header.snowProbability,
    fogProbability: raw.header.fogProbability,
    lightningProbability: raw.header.lightningProbability,
    overlayTransparency: raw.header.overlayTransparency,
    areaScript: raw.header.areaScript,
    restMovieDay: raw.header.restMovieDay,
    restMovieNight: raw.header.restMovieNight,
  },
  actors: raw.actors.map(toActor),
  regions: raw.regions.map(toRegion),
  spawnPoints: raw.spawnPoints.map(toSpawnPoint),
  entrances: raw.entrances.map(entrance => ({
    name: entrance.name,
    at: entrance.at,
    direction: entrance.direction,
  })),
  containers: raw.containers.map(toContainer),
  ambients: raw.ambients.map(toAmbient),
  variables: raw.variables.map(variable => ({
    name: variable.name,
    type: variable.type,
    resourceType: variable.resourceType,
    dwordValue: variable.dwordValue,
    intValue: variable.intValue,
    doubleValue: variable.doubleValue,
    scriptNameValue: variable.scriptNameValue,
  })),
  exploredBitmaskName: raw.exploredBitmaskName,
  doors: raw.doors.map(toDoor),
  animations: raw.animations.map(toAnimation),
  automapNotes: raw.automapNotes.map(note => ({
    at: note.at,
    textRef: note.textRef,
    strrefLocation: note.strrefLocation,
    markerColor: note.markerColor,
    controlId: note.controlId,
  })),
  tiledObjects: raw.tiledObjects.map(toTiledObject),
  projectileTraps: raw.projectileTraps.map(trap => ({
    projectile: trap.projectile,
    missileId: trap.missileId,
    ticksUntilCheck: trap.ticksUntilCheck,
    triggersRemaining: trap.triggersRemaining,
    x: trap.x,
    y: trap.y,
    z: trap.z,
    enemyAlly: trap.enemyAlly,
    indexOfPartyMemberWhoCreatedIt: trap.indexOfPartyMemberWhoCreatedIt,
  })),
  song: isNothing(raw.song)
    ? raw.song
    : {
        daySong: raw.song.daySong,
        nightSong: raw.song.nightSong,
        winSong: raw.song.winSong,
        battleSong: raw.song.battleSong,
        loseSong: raw.song.loseSong,
        altMusic1: raw.song.altMusic1,
        altMusic2: raw.song.altMusic2,
        altMusic3: raw.song.altMusic3,
        altMusic4: raw.song.altMusic4,
        altMusic5: raw.song.altMusic5,
        mainDayAmbient1: raw.song.mainDayAmbient1,
        mainDayAmbient2: raw.song.mainDayAmbient2,
        mainDayAmbientVolume: raw.song.mainDayAmbientVolume,
        mainNightAmbient1: raw.song.mainNightAmbient1,
        mainNightAmbient2: raw.song.mainNightAmbient2,
        mainNightAmbientVolume: raw.song.mainNightAmbientVolume,
        reverb: raw.song.reverb,
      },
  restInterruptions: isNothing(raw.restInterruptions)
    ? raw.restInterruptions
    : toRestInterruptions(raw.restInterruptions),
});
