/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

export const dlg_dlgId_skeletonSchema = {
    type: 'string',
    minLength: 1,
    example: 'dmorte1.dlg'
} as const;

export const cre_creId_skeletonSchema = {
    type: 'string',
    minLength: 1,
    example: 'morte.cre'
} as const;

export const cre_creId_gameLanguageSchema = {
    type: 'string',
    minLength: 1,
    example: 'morte.cre'
} as const;

export const gameLanguageSchema = {
    type: 'string',
    enum: [
        'ru_RU',
        'en_US',
        'cs_CZ',
        'de_DE',
        'fr_FR',
        'ko_KR',
        'pl_PL'
    ],
    example: 'ru_RU'
} as const;

export const itm_itmId_skeletonSchema = {
    type: 'string',
    minLength: 1,
    example: 'charchrm.itm'
} as const;

export const itm_itmId_gameLanguageSchema = {
    type: 'string',
    minLength: 1,
    example: 'charchrm.itm'
} as const;

export const bcs_bcsIdSchema = {
    type: 'string',
    minLength: 1,
    example: '0202cs2.bcs'
} as const;

export const mos_mosIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'ar0202.mos'
} as const;

export const pvrz_pvrzIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'a020301.pvrz'
} as const;

export const tis_tisIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'ar0202.tis'
} as const;

export const wed_wedIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'ar0202.wed'
} as const;

export const acm_acmIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'baator.acm'
} as const;

export const bam_bamIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'ampnm1.bam'
} as const;

export const bmp_bmpIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'ampnm1.bmp'
} as const;

export const wav_wavIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'nam157.wav'
} as const;

export const mus_musIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'baat.mus'
} as const;

export const eff_effIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'spin103.eff'
} as const;

export const ids_idsIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'class.ids'
} as const;

export const ini_iniIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'ar0202.ini'
} as const;

export const creToDlgs_creIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'morte.cre'
} as const;

export const dlgToCre_dlgIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'dmorte1.dlg'
} as const;

export const itmToDlgs_itmIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'cube.itm'
} as const;

export const dlgToItm_dlgIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'dcube.dlg'
} as const;
