// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { GetApiPingData, GetApiPingResponses, PostApiFsValidateChitinKeyPathData, PostApiFsValidateChitinKeyPathErrors, PostApiFsValidateChitinKeyPathResponses, PostApiFsValidateWeiduPathData, PostApiFsValidateWeiduPathErrors, PostApiFsValidateWeiduPathResponses, PostApiGhostDialogueByDialogueIdByGameLanguageData, PostApiGhostDialogueByDialogueIdByGameLanguageErrors, PostApiGhostDialogueByDialogueIdByGameLanguageResponses, PostApiGhostDialogueByDialogueIdSkeletonData, PostApiGhostDialogueByDialogueIdSkeletonErrors, PostApiGhostDialogueByDialogueIdSkeletonResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Validates CHITIN.key folder as a game folder
 */
export const postApiFsValidateChitinKeyPath = <ThrowOnError extends boolean = false>(options: Options<PostApiFsValidateChitinKeyPathData, ThrowOnError>) => (options.client ?? client).post<PostApiFsValidateChitinKeyPathResponses, PostApiFsValidateChitinKeyPathErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/fs/validate/chitinKeyPath',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Validates weidu.exe access
 */
export const postApiFsValidateWeiduPath = <ThrowOnError extends boolean = false>(options: Options<PostApiFsValidateWeiduPathData, ThrowOnError>) => (options.client ?? client).post<PostApiFsValidateWeiduPathResponses, PostApiFsValidateWeiduPathErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/fs/validate/weiduPath',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Ping
 */
export const getApiPing = <ThrowOnError extends boolean = false>(options?: Options<GetApiPingData, ThrowOnError>) => (options?.client ?? client).get<GetApiPingResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/ping',
    ...options
});

/**
 * Get skeleton of the dialogue in ghost format
 */
export const postApiGhostDialogueByDialogueIdSkeleton = <ThrowOnError extends boolean = false>(options: Options<PostApiGhostDialogueByDialogueIdSkeletonData, ThrowOnError>) => (options.client ?? client).post<PostApiGhostDialogueByDialogueIdSkeletonResponses, PostApiGhostDialogueByDialogueIdSkeletonErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/ghost/dialogue/{dialogueId}/skeleton',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get translation of the dialogue in ghost format
 */
export const postApiGhostDialogueByDialogueIdByGameLanguage = <ThrowOnError extends boolean = false>(options: Options<PostApiGhostDialogueByDialogueIdByGameLanguageData, ThrowOnError>) => (options.client ?? client).post<PostApiGhostDialogueByDialogueIdByGameLanguageResponses, PostApiGhostDialogueByDialogueIdByGameLanguageErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/ghost/dialogue/{dialogueId}/{gameLanguage}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
