// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3003' | (string & {});
};

export type DialogueId = string;

export const GameLanguage = {
    RU_RU: 'ru_RU',
    EN_US: 'en_US',
    CS_CZ: 'cs_CZ',
    DE_DE: 'de_DE',
    FR_FR: 'fr_FR',
    KO_KR: 'ko_KR',
    PL_PL: 'pl_PL'
} as const;

export type GameLanguage = typeof GameLanguage[keyof typeof GameLanguage];

export type CreatureId = string;

/**
 * Dialogue id
 */
export type DialogueId2 = DialogueId & unknown;

/**
 * Skeleton creature language
 */
export type GameLanguage2 = GameLanguage;

/**
 * Creature id
 */
export type CreatureId2 = CreatureId & unknown;

export type PostApiFsValidateChitinKeyFileData = {
    body: {
        weiduExeDir: string;
        chitinKeyFile: string;
        gameLanguage: 'ru_RU' | 'en_US' | 'cs_CZ' | 'de_DE' | 'fr_FR' | 'ko_KR' | 'pl_PL';
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/chitinKeyFile';
};

export type PostApiFsValidateChitinKeyFileErrors = {
    /**
     * Game directory is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'NO_BIFFS';
        };
    };
};

export type PostApiFsValidateChitinKeyFileError = PostApiFsValidateChitinKeyFileErrors[keyof PostApiFsValidateChitinKeyFileErrors];

export type PostApiFsValidateChitinKeyFileResponses = {
    /**
     * How many biffs are found by weidu in the game directory
     */
    200: {
        data: {
            biffsCount: number;
        };
    };
};

export type PostApiFsValidateChitinKeyFileResponse = PostApiFsValidateChitinKeyFileResponses[keyof PostApiFsValidateChitinKeyFileResponses];

export type PostApiFsValidateGhostDirData = {
    body: {
        ghostDir: string;
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/ghostDir';
};

export type PostApiFsValidateGhostDirErrors = {
    /**
     * Ghost directory not found
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'DIRECTORY_NOT_EMPTY';
        };
    };
    /**
     * Ghost directory not empty
     */
    406: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'DIRECTORY_NOT_EMPTY';
        };
    };
};

export type PostApiFsValidateGhostDirError = PostApiFsValidateGhostDirErrors[keyof PostApiFsValidateGhostDirErrors];

export type PostApiFsValidateGhostDirResponses = {
    /**
     * Ghost is valid
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostApiFsValidateGhostDirResponse = PostApiFsValidateGhostDirResponses[keyof PostApiFsValidateGhostDirResponses];

export type PostApiFsValidateWeiduExeDirData = {
    body: {
        weiduExeDir: string;
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/weiduExeDir';
};

export type PostApiFsValidateWeiduExeDirErrors = {
    /**
     * Weidu error
     */
    400: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'WEIDU_ERROR';
        };
    };
    /**
     * Weidu not found
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'WEIDU_ERROR';
        };
    };
};

export type PostApiFsValidateWeiduExeDirError = PostApiFsValidateWeiduExeDirErrors[keyof PostApiFsValidateWeiduExeDirErrors];

export type PostApiFsValidateWeiduExeDirResponses = {
    /**
     * Weidu.exe version
     */
    200: {
        data: {
            version: string;
        };
    };
};

export type PostApiFsValidateWeiduExeDirResponse = PostApiFsValidateWeiduExeDirResponses[keyof PostApiFsValidateWeiduExeDirResponses];

export type GetApiFsGhostDirByFilePathData = {
    body?: never;
    path: {
        /**
         * Relative path to the file relative to ghost directory, can include lower slashes
         */
        filePath: string;
    };
    query?: never;
    url: '/api/fs/ghostDir/{filePath}';
};

export type GetApiFsGhostDirByFilePathErrors = {
    /**
     * Forbidden relative path in the ghost directory
     */
    403: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
    /**
     * No such file in the ghost directory
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
};

export type GetApiFsGhostDirByFilePathError = GetApiFsGhostDirByFilePathErrors[keyof GetApiFsGhostDirByFilePathErrors];

export type GetApiFsGhostDirByFilePathResponses = {
    /**
     * File content from ghost directory
     */
    200: string;
};

export type GetApiFsGhostDirByFilePathResponse = GetApiFsGhostDirByFilePathResponses[keyof GetApiFsGhostDirByFilePathResponses];

export type GetApiFsPrismDirByFilePathData = {
    body?: never;
    path: {
        /**
         * Relative path to the file relative to prism directory, can include lower slashes
         */
        filePath: string;
    };
    query?: never;
    url: '/api/fs/prismDir/{filePath}';
};

export type GetApiFsPrismDirByFilePathErrors = {
    /**
     * Forbidden relative path in the prism directory
     */
    403: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
    /**
     * No such file in the prism directory
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
};

export type GetApiFsPrismDirByFilePathError = GetApiFsPrismDirByFilePathErrors[keyof GetApiFsPrismDirByFilePathErrors];

export type GetApiFsPrismDirByFilePathResponses = {
    /**
     * File content from prism directory
     */
    200: string;
};

export type GetApiFsPrismDirByFilePathResponse = GetApiFsPrismDirByFilePathResponses[keyof GetApiFsPrismDirByFilePathResponses];

export type GetApiFsShellDirByFilePathData = {
    body?: never;
    path?: {
        /**
         * Relative path to the file relative to shell directory, can include lower slashes
         */
        filePath?: string;
    };
    query?: never;
    url: '/api/fs/shellDir/{filePath}';
};

export type GetApiFsShellDirByFilePathErrors = {
    /**
     * Forbidden relative path in the shell directory
     */
    403: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
    /**
     * No such file in the shell directory
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
};

export type GetApiFsShellDirByFilePathError = GetApiFsShellDirByFilePathErrors[keyof GetApiFsShellDirByFilePathErrors];

export type GetApiFsShellDirByFilePathResponses = {
    /**
     * File content from shell directory
     */
    200: string;
};

export type GetApiFsShellDirByFilePathResponse = GetApiFsShellDirByFilePathResponses[keyof GetApiFsShellDirByFilePathResponses];

export type GetApiPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ping';
};

export type GetApiPingResponses = {
    /**
     * pong asclepius
     */
    200: 'pong asclepius';
};

export type GetApiPingResponse = GetApiPingResponses[keyof GetApiPingResponses];

export type PostApiGhostDialogueByDialogueIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Dialogue id
         */
        dialogueId: DialogueId & unknown;
    };
    query?: never;
    url: '/api/ghost/dialogue/{dialogueId}/skeleton';
};

export type PostApiGhostDialogueByDialogueIdSkeletonErrors = {
    /**
     * Dialogue skeleton is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostDialogueByDialogueIdSkeletonError = PostApiGhostDialogueByDialogueIdSkeletonErrors[keyof PostApiGhostDialogueByDialogueIdSkeletonErrors];

export type PostApiGhostDialogueByDialogueIdSkeletonResponses = {
    /**
     * Dialogue skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostDialogueByDialogueIdSkeletonResponse = PostApiGhostDialogueByDialogueIdSkeletonResponses[keyof PostApiGhostDialogueByDialogueIdSkeletonResponses];

export type PostApiGhostDialogueByDialogueIdByGameLanguageData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Dialogue id
         */
        dialogueId: DialogueId & unknown;
        /**
         * Skeleton creature language
         */
        gameLanguage: GameLanguage;
    };
    query?: never;
    url: '/api/ghost/dialogue/{dialogueId}/{gameLanguage}';
};

export type PostApiGhostDialogueByDialogueIdByGameLanguageErrors = {
    /**
     * Dialogue translation is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostDialogueByDialogueIdByGameLanguageError = PostApiGhostDialogueByDialogueIdByGameLanguageErrors[keyof PostApiGhostDialogueByDialogueIdByGameLanguageErrors];

export type PostApiGhostDialogueByDialogueIdByGameLanguageResponses = {
    /**
     * Dialogue translation content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostDialogueByDialogueIdByGameLanguageResponse = PostApiGhostDialogueByDialogueIdByGameLanguageResponses[keyof PostApiGhostDialogueByDialogueIdByGameLanguageResponses];

export type PostApiGhostDialogueData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/dialogue';
};

export type PostApiGhostDialogueErrors = {
    /**
     * Available dialogues are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostDialogueError = PostApiGhostDialogueErrors[keyof PostApiGhostDialogueErrors];

export type PostApiGhostDialogueResponses = {
    /**
     * Available dialogues in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostDialogueResponse = PostApiGhostDialogueResponses[keyof PostApiGhostDialogueResponses];

export type PostApiGhostCreatureByCreatureIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Creature id
         */
        creatureId: CreatureId & unknown;
    };
    query?: never;
    url: '/api/ghost/creature/{creatureId}/skeleton';
};

export type PostApiGhostCreatureByCreatureIdSkeletonErrors = {
    /**
     * Creature skeleton is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostCreatureByCreatureIdSkeletonError = PostApiGhostCreatureByCreatureIdSkeletonErrors[keyof PostApiGhostCreatureByCreatureIdSkeletonErrors];

export type PostApiGhostCreatureByCreatureIdSkeletonResponses = {
    /**
     * Creature skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostCreatureByCreatureIdSkeletonResponse = PostApiGhostCreatureByCreatureIdSkeletonResponses[keyof PostApiGhostCreatureByCreatureIdSkeletonResponses];

export type PostApiGhostCreatureByCreatureIdByGameLanguageData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Creature id
         */
        creatureId: CreatureId & unknown;
        /**
         * Skeleton creature language
         */
        gameLanguage: GameLanguage;
    };
    query?: never;
    url: '/api/ghost/creature/{creatureId}/{gameLanguage}';
};

export type PostApiGhostCreatureByCreatureIdByGameLanguageErrors = {
    /**
     * Creature translation is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostCreatureByCreatureIdByGameLanguageError = PostApiGhostCreatureByCreatureIdByGameLanguageErrors[keyof PostApiGhostCreatureByCreatureIdByGameLanguageErrors];

export type PostApiGhostCreatureByCreatureIdByGameLanguageResponses = {
    /**
     * Creature translation content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostCreatureByCreatureIdByGameLanguageResponse = PostApiGhostCreatureByCreatureIdByGameLanguageResponses[keyof PostApiGhostCreatureByCreatureIdByGameLanguageResponses];

export type PostApiGhostCreatureData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/creature';
};

export type PostApiGhostCreatureErrors = {
    /**
     * Available creatures are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostCreatureError = PostApiGhostCreatureErrors[keyof PostApiGhostCreatureErrors];

export type PostApiGhostCreatureResponses = {
    /**
     * Available creatures in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostCreatureResponse = PostApiGhostCreatureResponses[keyof PostApiGhostCreatureResponses];

export type GetApiMapCreatureToDialoguesByCreatureIdData = {
    body?: never;
    path: {
        /**
         * Creature id
         */
        creatureId: CreatureId & unknown;
    };
    query?: never;
    url: '/api/map/creatureToDialogues/{creatureId}';
};

export type GetApiMapCreatureToDialoguesByCreatureIdErrors = {
    /**
     * Dialogues ids were not found for the creature id
     */
    404: {
        error: {
            message: string;
            code: 'DIALOGUES_NOT_FOUND';
        };
    };
};

export type GetApiMapCreatureToDialoguesByCreatureIdError = GetApiMapCreatureToDialoguesByCreatureIdErrors[keyof GetApiMapCreatureToDialoguesByCreatureIdErrors];

export type GetApiMapCreatureToDialoguesByCreatureIdResponses = {
    /**
     * Dialogues ids
     */
    200: Array<string>;
};

export type GetApiMapCreatureToDialoguesByCreatureIdResponse = GetApiMapCreatureToDialoguesByCreatureIdResponses[keyof GetApiMapCreatureToDialoguesByCreatureIdResponses];

export type GetApiMapDialogueToCreatureByDialogueIdData = {
    body?: never;
    path: {
        /**
         * Dialogue id
         */
        dialogueId: DialogueId & unknown;
    };
    query?: never;
    url: '/api/map/dialogueToCreature/{dialogueId}';
};

export type GetApiMapDialogueToCreatureByDialogueIdErrors = {
    /**
     * Creature id were not found for this dialogue id
     */
    404: {
        error: {
            message: string;
            code: 'CREATURE_NOT_FOUND';
        };
    };
};

export type GetApiMapDialogueToCreatureByDialogueIdError = GetApiMapDialogueToCreatureByDialogueIdErrors[keyof GetApiMapDialogueToCreatureByDialogueIdErrors];

export type GetApiMapDialogueToCreatureByDialogueIdResponses = {
    /**
     * Creature id
     */
    200: string;
};

export type GetApiMapDialogueToCreatureByDialogueIdResponse = GetApiMapDialogueToCreatureByDialogueIdResponses[keyof GetApiMapDialogueToCreatureByDialogueIdResponses];

export type GetApiSettingsGhostDirData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/ghostDir';
};

export type GetApiSettingsGhostDirResponses = {
    /**
     * Current ghost directory path settings
     */
    200: {
        ghostDir: string;
    };
};

export type GetApiSettingsGhostDirResponse = GetApiSettingsGhostDirResponses[keyof GetApiSettingsGhostDirResponses];

export type PostApiSettingsGhostDirData = {
    body: {
        ghostDir: string;
    };
    path?: never;
    query?: never;
    url: '/api/settings/ghostDir';
};

export type PostApiSettingsGhostDirErrors = {
    /**
     * No such directory for ghost directory
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiSettingsGhostDirError = PostApiSettingsGhostDirErrors[keyof PostApiSettingsGhostDirErrors];

export type PostApiSettingsGhostDirResponses = {
    /**
     * Current ghost directory path settings
     */
    200: {
        ghostDir: string;
    };
};

export type PostApiSettingsGhostDirResponse = PostApiSettingsGhostDirResponses[keyof PostApiSettingsGhostDirResponses];

export type GetApiSettingsPrismDirData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/prismDir';
};

export type GetApiSettingsPrismDirResponses = {
    /**
     * Current prism directory path settings
     */
    200: {
        prismDir: string;
    };
};

export type GetApiSettingsPrismDirResponse = GetApiSettingsPrismDirResponses[keyof GetApiSettingsPrismDirResponses];

export type PostApiSettingsPrismDirData = {
    body: {
        prismDir: string;
    };
    path?: never;
    query?: never;
    url: '/api/settings/prismDir';
};

export type PostApiSettingsPrismDirErrors = {
    /**
     * No such directory for prism directory
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiSettingsPrismDirError = PostApiSettingsPrismDirErrors[keyof PostApiSettingsPrismDirErrors];

export type PostApiSettingsPrismDirResponses = {
    /**
     * Current prism directory path settings
     */
    200: {
        prismDir: string;
    };
};

export type PostApiSettingsPrismDirResponse = PostApiSettingsPrismDirResponses[keyof PostApiSettingsPrismDirResponses];

export type GetApiSettingsShellDirData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/shellDir';
};

export type GetApiSettingsShellDirResponses = {
    /**
     * Current shell directory path settings
     */
    200: {
        shellDir: string;
    };
};

export type GetApiSettingsShellDirResponse = GetApiSettingsShellDirResponses[keyof GetApiSettingsShellDirResponses];

export type PostApiSettingsShellDirData = {
    body: {
        shellDir: string;
    };
    path?: never;
    query?: never;
    url: '/api/settings/shellDir';
};

export type PostApiSettingsShellDirErrors = {
    /**
     * No such directory for shell directory
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiSettingsShellDirError = PostApiSettingsShellDirErrors[keyof PostApiSettingsShellDirErrors];

export type PostApiSettingsShellDirResponses = {
    /**
     * Current shell directory path settings
     */
    200: {
        shellDir: string;
    };
};

export type PostApiSettingsShellDirResponse = PostApiSettingsShellDirResponses[keyof PostApiSettingsShellDirResponses];
