/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3003' | (string & {});
};

export type DlgDlgIdSkeleton = string;

export type CreCreIdSkeleton = string;

export type CreCreIdGameLanguage = string;

export const GameLanguage = {
    RU_RU: 'ru_RU',
    EN_US: 'en_US',
    CS_CZ: 'cs_CZ',
    DE_DE: 'de_DE',
    FR_FR: 'fr_FR',
    KO_KR: 'ko_KR',
    PL_PL: 'pl_PL'
} as const;

export type GameLanguage = typeof GameLanguage[keyof typeof GameLanguage];

export type ItmItmIdSkeleton = string;

export type ItmItmIdGameLanguage = string;

export type BcsBcsId = string;

export type MosMosId = string;

export type PvrzPvrzId = string;

export type TisTisId = string;

export type WedWedId = string;

export type AcmAcmId = string;

export type BamBamId = string;

export type BmpBmpId = string;

export type WavWavId = string;

export type MusMusId = string;

export type EffEffId = string;

export type IdsIdsId = string;

export type IniIniId = string;

export type AreAreId = string;

export type TwodaTwodaId = string;

export type SrcSrcId = string;

export type CreToDlgsCreId = string;

export type DlgToCreDlgId = string;

export type ItmToDlgsItmId = string;

export type DlgToItmDlgId = string;

/**
 * Skeleton dlg id
 */
export type DlgDlgIdSkeleton2 = DlgDlgIdSkeleton;

/**
 * Skeleton cre id
 */
export type CreCreIdSkeleton2 = CreCreIdSkeleton;

/**
 * Skeleton cre id
 */
export type CreCreIdGameLanguage2 = CreCreIdGameLanguage;

/**
 * Tlk language
 */
export type GameLanguage2 = GameLanguage;

/**
 * Skeleton itm id
 */
export type ItmItmIdSkeleton2 = ItmItmIdSkeleton;

/**
 * Skeleton itm id
 */
export type ItmItmIdGameLanguage2 = ItmItmIdGameLanguage;

/**
 * Bcs id
 */
export type BcsBcsId2 = BcsBcsId;

/**
 * Mos id
 */
export type MosMosId2 = MosMosId;

/**
 * Pvrz id
 */
export type PvrzPvrzId2 = PvrzPvrzId;

/**
 * Tis id
 */
export type TisTisId2 = TisTisId;

/**
 * Wed id
 */
export type WedWedId2 = WedWedId;

/**
 * Acm id
 */
export type AcmAcmId2 = AcmAcmId;

/**
 * Bam id
 */
export type BamBamId2 = BamBamId;

/**
 * Bmp id
 */
export type BmpBmpId2 = BmpBmpId;

/**
 * Wav id
 */
export type WavWavId2 = WavWavId;

/**
 * Mus id
 */
export type MusMusId2 = MusMusId;

/**
 * Eff id
 */
export type EffEffId2 = EffEffId;

/**
 * Ids id
 */
export type IdsIdsId2 = IdsIdsId;

/**
 * Ini id
 */
export type IniIniId2 = IniIniId;

/**
 * Are id
 */
export type AreAreId2 = AreAreId;

/**
 * 2da id
 */
export type TwodaTwodaId2 = TwodaTwodaId;

/**
 * Src id
 */
export type SrcSrcId2 = SrcSrcId;

/**
 * Cre id
 */
export type CreToDlgsCreId2 = CreToDlgsCreId;

/**
 * Dlg id
 */
export type DlgToCreDlgId2 = DlgToCreDlgId;

/**
 * Itm id
 */
export type ItmToDlgsItmId2 = ItmToDlgsItmId;

/**
 * Dlg id
 */
export type DlgToItmDlgId2 = DlgToItmDlgId;

export type PostApiFsValidateChitinKeyFileData = {
    body: {
        weiduExeDir: string;
        chitinKeyFile: string;
        gameLanguage: 'ru_RU' | 'en_US' | 'cs_CZ' | 'de_DE' | 'fr_FR' | 'ko_KR' | 'pl_PL';
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/chitinKeyFile';
};

export type PostApiFsValidateChitinKeyFileErrors = {
    /**
     * Game directory is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'NO_BIFFS';
        };
    };
};

export type PostApiFsValidateChitinKeyFileError = PostApiFsValidateChitinKeyFileErrors[keyof PostApiFsValidateChitinKeyFileErrors];

export type PostApiFsValidateChitinKeyFileResponses = {
    /**
     * How many biffs are found by weidu in the game directory
     */
    200: {
        data: {
            biffsCount: number;
        };
    };
};

export type PostApiFsValidateChitinKeyFileResponse = PostApiFsValidateChitinKeyFileResponses[keyof PostApiFsValidateChitinKeyFileResponses];

export type PostApiFsValidateGhostDirData = {
    body: {
        ghostDir: string;
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/ghostDir';
};

export type PostApiFsValidateGhostDirErrors = {
    /**
     * Ghost directory not found
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'DIRECTORY_NOT_EMPTY';
        };
    };
    /**
     * Ghost directory not empty
     */
    406: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'DIRECTORY_NOT_EMPTY';
        };
    };
};

export type PostApiFsValidateGhostDirError = PostApiFsValidateGhostDirErrors[keyof PostApiFsValidateGhostDirErrors];

export type PostApiFsValidateGhostDirResponses = {
    /**
     * Ghost is valid
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostApiFsValidateGhostDirResponse = PostApiFsValidateGhostDirResponses[keyof PostApiFsValidateGhostDirResponses];

export type PostApiFsValidateWeiduExeDirData = {
    body: {
        weiduExeDir: string;
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/weiduExeDir';
};

export type PostApiFsValidateWeiduExeDirErrors = {
    /**
     * Weidu error
     */
    400: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'WEIDU_ERROR';
        };
    };
    /**
     * Weidu not found
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'WEIDU_ERROR';
        };
    };
};

export type PostApiFsValidateWeiduExeDirError = PostApiFsValidateWeiduExeDirErrors[keyof PostApiFsValidateWeiduExeDirErrors];

export type PostApiFsValidateWeiduExeDirResponses = {
    /**
     * Weidu.exe version
     */
    200: {
        data: {
            version: string;
        };
    };
};

export type PostApiFsValidateWeiduExeDirResponse = PostApiFsValidateWeiduExeDirResponses[keyof PostApiFsValidateWeiduExeDirResponses];

export type PostApiFsDownloadWeiduData = {
    body: {
        platform: 'windows' | 'linux' | 'mac';
    };
    path?: never;
    query?: never;
    url: '/api/fs/download/weidu';
};

export type PostApiFsDownloadWeiduErrors = {
    /**
     * WeiDU binary not found in archive
     */
    404: {
        error: {
            message: string;
            code: 'DOWNLOAD_FAILED' | 'EXTRACT_FAILED' | 'BINARY_NOT_FOUND';
        };
    };
    /**
     * Failed to extract WeiDU
     */
    500: {
        error: {
            message: string;
            code: 'DOWNLOAD_FAILED' | 'EXTRACT_FAILED' | 'BINARY_NOT_FOUND';
        };
    };
    /**
     * Failed to download WeiDU
     */
    502: {
        error: {
            message: string;
            code: 'DOWNLOAD_FAILED' | 'EXTRACT_FAILED' | 'BINARY_NOT_FOUND';
        };
    };
};

export type PostApiFsDownloadWeiduError = PostApiFsDownloadWeiduErrors[keyof PostApiFsDownloadWeiduErrors];

export type PostApiFsDownloadWeiduResponses = {
    /**
     * Path to the WeiDU binary
     */
    200: {
        data: {
            weiduExeDir: string;
        };
    };
};

export type PostApiFsDownloadWeiduResponse = PostApiFsDownloadWeiduResponses[keyof PostApiFsDownloadWeiduResponses];

export type PostApiFsOpenDirData = {
    body: {
        dir: string;
    };
    path?: never;
    query?: never;
    url: '/api/fs/openDir';
};

export type PostApiFsOpenDirErrors = {
    /**
     * Path is not a directory
     */
    400: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'NOT_A_DIRECTORY' | 'OPEN_FAILED';
        };
    };
    /**
     * Directory not found
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'NOT_A_DIRECTORY' | 'OPEN_FAILED';
        };
    };
    /**
     * Failed to open directory
     */
    500: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'NOT_A_DIRECTORY' | 'OPEN_FAILED';
        };
    };
};

export type PostApiFsOpenDirError = PostApiFsOpenDirErrors[keyof PostApiFsOpenDirErrors];

export type PostApiFsOpenDirResponses = {
    /**
     * Directory opened
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostApiFsOpenDirResponse = PostApiFsOpenDirResponses[keyof PostApiFsOpenDirResponses];

export type GetApiFsGhostDirByFilePathData = {
    body?: never;
    path: {
        /**
         * Relative path to the file relative to ghost directory, can include lower slashes
         */
        filePath: string;
    };
    query?: never;
    url: '/api/fs/ghostDir/{filePath}';
};

export type GetApiFsGhostDirByFilePathErrors = {
    /**
     * Forbidden relative path in the ghost directory
     */
    403: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
    /**
     * No such file in the ghost directory
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
};

export type GetApiFsGhostDirByFilePathError = GetApiFsGhostDirByFilePathErrors[keyof GetApiFsGhostDirByFilePathErrors];

export type GetApiFsGhostDirByFilePathResponses = {
    /**
     * File content from ghost directory
     */
    200: string;
};

export type GetApiFsGhostDirByFilePathResponse = GetApiFsGhostDirByFilePathResponses[keyof GetApiFsGhostDirByFilePathResponses];

export type GetApiFsPrismDirByFilePathData = {
    body?: never;
    path: {
        /**
         * Relative path to the file relative to prism directory, can include lower slashes
         */
        filePath: string;
    };
    query?: never;
    url: '/api/fs/prismDir/{filePath}';
};

export type GetApiFsPrismDirByFilePathErrors = {
    /**
     * Forbidden relative path in the prism directory
     */
    403: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
    /**
     * No such file in the prism directory
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
};

export type GetApiFsPrismDirByFilePathError = GetApiFsPrismDirByFilePathErrors[keyof GetApiFsPrismDirByFilePathErrors];

export type GetApiFsPrismDirByFilePathResponses = {
    /**
     * File content from prism directory
     */
    200: string;
};

export type GetApiFsPrismDirByFilePathResponse = GetApiFsPrismDirByFilePathResponses[keyof GetApiFsPrismDirByFilePathResponses];

export type GetApiFsShellDirByFilePathData = {
    body?: never;
    path?: {
        /**
         * Relative path to the file relative to shell directory, can include lower slashes
         */
        filePath?: string;
    };
    query?: never;
    url: '/api/fs/shellDir/{filePath}';
};

export type GetApiFsShellDirByFilePathErrors = {
    /**
     * Forbidden relative path in the shell directory
     */
    403: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
    /**
     * No such file in the shell directory
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
};

export type GetApiFsShellDirByFilePathError = GetApiFsShellDirByFilePathErrors[keyof GetApiFsShellDirByFilePathErrors];

export type GetApiFsShellDirByFilePathResponses = {
    /**
     * File content from shell directory
     */
    200: string;
};

export type GetApiFsShellDirByFilePathResponse = GetApiFsShellDirByFilePathResponses[keyof GetApiFsShellDirByFilePathResponses];

export type GetApiAssetsByFilePathData = {
    body?: never;
    path: {
        /**
         * Relative path to the file in assets directory
         */
        filePath: string;
    };
    query?: never;
    url: '/api/assets/{filePath}';
};

export type GetApiAssetsByFilePathErrors = {
    /**
     * Forbidden relative path in the assets directory
     */
    403: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
    /**
     * No such file in the assets directory
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
};

export type GetApiAssetsByFilePathError = GetApiAssetsByFilePathErrors[keyof GetApiAssetsByFilePathErrors];

export type GetApiAssetsByFilePathResponses = {
    /**
     * File content from assets directory
     */
    200: Blob | File;
};

export type GetApiAssetsByFilePathResponse = GetApiAssetsByFilePathResponses[keyof GetApiAssetsByFilePathResponses];

export type GetApiPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ping';
};

export type GetApiPingResponses = {
    /**
     * pong asclepius
     */
    200: 'pong asclepius';
};

export type GetApiPingResponse = GetApiPingResponses[keyof GetApiPingResponses];

export type PostApiGhostDlgByDlgIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Skeleton dlg id
         */
        dlgId: DlgDlgIdSkeleton;
    };
    query?: never;
    url: '/api/ghost/dlg/{dlgId}/skeleton';
};

export type PostApiGhostDlgByDlgIdSkeletonErrors = {
    /**
     * Dlg skeleton is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostDlgByDlgIdSkeletonError = PostApiGhostDlgByDlgIdSkeletonErrors[keyof PostApiGhostDlgByDlgIdSkeletonErrors];

export type PostApiGhostDlgByDlgIdSkeletonResponses = {
    /**
     * Dlg skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostDlgByDlgIdSkeletonResponse = PostApiGhostDlgByDlgIdSkeletonResponses[keyof PostApiGhostDlgByDlgIdSkeletonResponses];

export type PostApiGhostDlgData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/dlg';
};

export type PostApiGhostDlgErrors = {
    /**
     * Available dlgs are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostDlgError = PostApiGhostDlgErrors[keyof PostApiGhostDlgErrors];

export type PostApiGhostDlgResponses = {
    /**
     * Available dlgs in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostDlgResponse = PostApiGhostDlgResponses[keyof PostApiGhostDlgResponses];

export type PostApiGhostCreByCreIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Skeleton cre id
         */
        creId: CreCreIdSkeleton;
    };
    query?: never;
    url: '/api/ghost/cre/{creId}/skeleton';
};

export type PostApiGhostCreByCreIdSkeletonErrors = {
    /**
     * Cre skeleton is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostCreByCreIdSkeletonError = PostApiGhostCreByCreIdSkeletonErrors[keyof PostApiGhostCreByCreIdSkeletonErrors];

export type PostApiGhostCreByCreIdSkeletonResponses = {
    /**
     * Cre skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostCreByCreIdSkeletonResponse = PostApiGhostCreByCreIdSkeletonResponses[keyof PostApiGhostCreByCreIdSkeletonResponses];

export type PostApiGhostCreByCreIdByGameLanguageData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Skeleton cre id
         */
        creId: CreCreIdGameLanguage;
        /**
         * Tlk language
         */
        gameLanguage: GameLanguage;
    };
    query?: never;
    url: '/api/ghost/cre/{creId}/{gameLanguage}';
};

export type PostApiGhostCreByCreIdByGameLanguageErrors = {
    /**
     * Cre translation is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostCreByCreIdByGameLanguageError = PostApiGhostCreByCreIdByGameLanguageErrors[keyof PostApiGhostCreByCreIdByGameLanguageErrors];

export type PostApiGhostCreByCreIdByGameLanguageResponses = {
    /**
     * Cre translation content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostCreByCreIdByGameLanguageResponse = PostApiGhostCreByCreIdByGameLanguageResponses[keyof PostApiGhostCreByCreIdByGameLanguageResponses];

export type PostApiGhostCreData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/cre';
};

export type PostApiGhostCreErrors = {
    /**
     * Available cres are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostCreError = PostApiGhostCreErrors[keyof PostApiGhostCreErrors];

export type PostApiGhostCreResponses = {
    /**
     * Available cres in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostCreResponse = PostApiGhostCreResponses[keyof PostApiGhostCreResponses];

export type PostApiGhostItmByItmIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Skeleton itm id
         */
        itmId: ItmItmIdSkeleton;
    };
    query?: never;
    url: '/api/ghost/itm/{itmId}/skeleton';
};

export type PostApiGhostItmByItmIdSkeletonErrors = {
    /**
     * Itm skeleton is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostItmByItmIdSkeletonError = PostApiGhostItmByItmIdSkeletonErrors[keyof PostApiGhostItmByItmIdSkeletonErrors];

export type PostApiGhostItmByItmIdSkeletonResponses = {
    /**
     * Itm skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostItmByItmIdSkeletonResponse = PostApiGhostItmByItmIdSkeletonResponses[keyof PostApiGhostItmByItmIdSkeletonResponses];

export type PostApiGhostItmByItmIdByGameLanguageData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Skeleton itm id
         */
        itmId: ItmItmIdGameLanguage;
        /**
         * Tlk language
         */
        gameLanguage: GameLanguage;
    };
    query?: never;
    url: '/api/ghost/itm/{itmId}/{gameLanguage}';
};

export type PostApiGhostItmByItmIdByGameLanguageErrors = {
    /**
     * Itm translation is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostItmByItmIdByGameLanguageError = PostApiGhostItmByItmIdByGameLanguageErrors[keyof PostApiGhostItmByItmIdByGameLanguageErrors];

export type PostApiGhostItmByItmIdByGameLanguageResponses = {
    /**
     * Itm translation content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostItmByItmIdByGameLanguageResponse = PostApiGhostItmByItmIdByGameLanguageResponses[keyof PostApiGhostItmByItmIdByGameLanguageResponses];

export type PostApiGhostItmData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/itm';
};

export type PostApiGhostItmErrors = {
    /**
     * Available itms are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostItmError = PostApiGhostItmErrors[keyof PostApiGhostItmErrors];

export type PostApiGhostItmResponses = {
    /**
     * Available itms in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostItmResponse = PostApiGhostItmResponses[keyof PostApiGhostItmResponses];

export type PostApiGhostBcsData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/bcs';
};

export type PostApiGhostBcsErrors = {
    /**
     * Available bcs are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostBcsError = PostApiGhostBcsErrors[keyof PostApiGhostBcsErrors];

export type PostApiGhostBcsResponses = {
    /**
     * Available bcs in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostBcsResponse = PostApiGhostBcsResponses[keyof PostApiGhostBcsResponses];

export type PostApiGhostBcsByBcsIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Bcs id
         */
        bcsId: BcsBcsId;
    };
    query?: never;
    url: '/api/ghost/bcs/{bcsId}/skeleton';
};

export type PostApiGhostBcsByBcsIdSkeletonErrors = {
    /**
     * Bcs is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostBcsByBcsIdSkeletonError = PostApiGhostBcsByBcsIdSkeletonErrors[keyof PostApiGhostBcsByBcsIdSkeletonErrors];

export type PostApiGhostBcsByBcsIdSkeletonResponses = {
    /**
     * Bcs skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostBcsByBcsIdSkeletonResponse = PostApiGhostBcsByBcsIdSkeletonResponses[keyof PostApiGhostBcsByBcsIdSkeletonResponses];

export type PostApiGhostMosData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/mos';
};

export type PostApiGhostMosErrors = {
    /**
     * Available mos are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostMosError = PostApiGhostMosErrors[keyof PostApiGhostMosErrors];

export type PostApiGhostMosResponses = {
    /**
     * Available mos in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostMosResponse = PostApiGhostMosResponses[keyof PostApiGhostMosResponses];

export type PostApiGhostMosByMosIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Mos id
         */
        mosId: MosMosId;
    };
    query?: never;
    url: '/api/ghost/mos/{mosId}/skeleton';
};

export type PostApiGhostMosByMosIdSkeletonErrors = {
    /**
     * Mos is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostMosByMosIdSkeletonError = PostApiGhostMosByMosIdSkeletonErrors[keyof PostApiGhostMosByMosIdSkeletonErrors];

export type PostApiGhostMosByMosIdSkeletonResponses = {
    /**
     * Mos skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostMosByMosIdSkeletonResponse = PostApiGhostMosByMosIdSkeletonResponses[keyof PostApiGhostMosByMosIdSkeletonResponses];

export type PostApiGhostPvrzData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/pvrz';
};

export type PostApiGhostPvrzErrors = {
    /**
     * Available pvrz are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostPvrzError = PostApiGhostPvrzErrors[keyof PostApiGhostPvrzErrors];

export type PostApiGhostPvrzResponses = {
    /**
     * Available pvrz in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostPvrzResponse = PostApiGhostPvrzResponses[keyof PostApiGhostPvrzResponses];

export type PostApiGhostPvrzByPvrzIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Pvrz id
         */
        pvrzId: PvrzPvrzId;
    };
    query?: never;
    url: '/api/ghost/pvrz/{pvrzId}/skeleton';
};

export type PostApiGhostPvrzByPvrzIdSkeletonErrors = {
    /**
     * Pvrz is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostPvrzByPvrzIdSkeletonError = PostApiGhostPvrzByPvrzIdSkeletonErrors[keyof PostApiGhostPvrzByPvrzIdSkeletonErrors];

export type PostApiGhostPvrzByPvrzIdSkeletonResponses = {
    /**
     * Pvrz skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostPvrzByPvrzIdSkeletonResponse = PostApiGhostPvrzByPvrzIdSkeletonResponses[keyof PostApiGhostPvrzByPvrzIdSkeletonResponses];

export type PostApiGhostTisData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/tis';
};

export type PostApiGhostTisErrors = {
    /**
     * Available tis are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostTisError = PostApiGhostTisErrors[keyof PostApiGhostTisErrors];

export type PostApiGhostTisResponses = {
    /**
     * Available tis in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostTisResponse = PostApiGhostTisResponses[keyof PostApiGhostTisResponses];

export type PostApiGhostTisByTisIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Tis id
         */
        tisId: TisTisId;
    };
    query?: never;
    url: '/api/ghost/tis/{tisId}/skeleton';
};

export type PostApiGhostTisByTisIdSkeletonErrors = {
    /**
     * Tis is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostTisByTisIdSkeletonError = PostApiGhostTisByTisIdSkeletonErrors[keyof PostApiGhostTisByTisIdSkeletonErrors];

export type PostApiGhostTisByTisIdSkeletonResponses = {
    /**
     * Tis skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostTisByTisIdSkeletonResponse = PostApiGhostTisByTisIdSkeletonResponses[keyof PostApiGhostTisByTisIdSkeletonResponses];

export type PostApiGhostWedData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/wed';
};

export type PostApiGhostWedErrors = {
    /**
     * Available wed are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostWedError = PostApiGhostWedErrors[keyof PostApiGhostWedErrors];

export type PostApiGhostWedResponses = {
    /**
     * Available wed in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostWedResponse = PostApiGhostWedResponses[keyof PostApiGhostWedResponses];

export type PostApiGhostWedByWedIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Wed id
         */
        wedId: WedWedId;
    };
    query?: never;
    url: '/api/ghost/wed/{wedId}/skeleton';
};

export type PostApiGhostWedByWedIdSkeletonErrors = {
    /**
     * Wed is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostWedByWedIdSkeletonError = PostApiGhostWedByWedIdSkeletonErrors[keyof PostApiGhostWedByWedIdSkeletonErrors];

export type PostApiGhostWedByWedIdSkeletonResponses = {
    /**
     * Wed skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostWedByWedIdSkeletonResponse = PostApiGhostWedByWedIdSkeletonResponses[keyof PostApiGhostWedByWedIdSkeletonResponses];

export type PostApiGhostAcmData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/acm';
};

export type PostApiGhostAcmErrors = {
    /**
     * Available acm are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostAcmError = PostApiGhostAcmErrors[keyof PostApiGhostAcmErrors];

export type PostApiGhostAcmResponses = {
    /**
     * Available acm in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostAcmResponse = PostApiGhostAcmResponses[keyof PostApiGhostAcmResponses];

export type PostApiGhostAcmByAcmIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Acm id
         */
        acmId: AcmAcmId;
    };
    query?: never;
    url: '/api/ghost/acm/{acmId}/skeleton';
};

export type PostApiGhostAcmByAcmIdSkeletonErrors = {
    /**
     * Acm is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostAcmByAcmIdSkeletonError = PostApiGhostAcmByAcmIdSkeletonErrors[keyof PostApiGhostAcmByAcmIdSkeletonErrors];

export type PostApiGhostAcmByAcmIdSkeletonResponses = {
    /**
     * Acm skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostAcmByAcmIdSkeletonResponse = PostApiGhostAcmByAcmIdSkeletonResponses[keyof PostApiGhostAcmByAcmIdSkeletonResponses];

export type PostApiGhostBamData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/bam';
};

export type PostApiGhostBamErrors = {
    /**
     * Available bam are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostBamError = PostApiGhostBamErrors[keyof PostApiGhostBamErrors];

export type PostApiGhostBamResponses = {
    /**
     * Available bam in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostBamResponse = PostApiGhostBamResponses[keyof PostApiGhostBamResponses];

export type PostApiGhostBamByBamIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Bam id
         */
        bamId: BamBamId;
    };
    query?: never;
    url: '/api/ghost/bam/{bamId}/skeleton';
};

export type PostApiGhostBamByBamIdSkeletonErrors = {
    /**
     * Bam is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostBamByBamIdSkeletonError = PostApiGhostBamByBamIdSkeletonErrors[keyof PostApiGhostBamByBamIdSkeletonErrors];

export type PostApiGhostBamByBamIdSkeletonResponses = {
    /**
     * Bam skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostBamByBamIdSkeletonResponse = PostApiGhostBamByBamIdSkeletonResponses[keyof PostApiGhostBamByBamIdSkeletonResponses];

export type PostApiGhostBmpData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/bmp';
};

export type PostApiGhostBmpErrors = {
    /**
     * Available bmp are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostBmpError = PostApiGhostBmpErrors[keyof PostApiGhostBmpErrors];

export type PostApiGhostBmpResponses = {
    /**
     * Available bmp in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostBmpResponse = PostApiGhostBmpResponses[keyof PostApiGhostBmpResponses];

export type PostApiGhostBmpByBmpIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Bmp id
         */
        bmpId: BmpBmpId;
    };
    query?: never;
    url: '/api/ghost/bmp/{bmpId}/skeleton';
};

export type PostApiGhostBmpByBmpIdSkeletonErrors = {
    /**
     * Bmp is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostBmpByBmpIdSkeletonError = PostApiGhostBmpByBmpIdSkeletonErrors[keyof PostApiGhostBmpByBmpIdSkeletonErrors];

export type PostApiGhostBmpByBmpIdSkeletonResponses = {
    /**
     * Bmp skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostBmpByBmpIdSkeletonResponse = PostApiGhostBmpByBmpIdSkeletonResponses[keyof PostApiGhostBmpByBmpIdSkeletonResponses];

export type PostApiGhostWavData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/wav';
};

export type PostApiGhostWavErrors = {
    /**
     * Available wav are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostWavError = PostApiGhostWavErrors[keyof PostApiGhostWavErrors];

export type PostApiGhostWavResponses = {
    /**
     * Available wav in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostWavResponse = PostApiGhostWavResponses[keyof PostApiGhostWavResponses];

export type PostApiGhostWavByWavIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Wav id
         */
        wavId: WavWavId;
    };
    query?: never;
    url: '/api/ghost/wav/{wavId}/skeleton';
};

export type PostApiGhostWavByWavIdSkeletonErrors = {
    /**
     * Wav is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostWavByWavIdSkeletonError = PostApiGhostWavByWavIdSkeletonErrors[keyof PostApiGhostWavByWavIdSkeletonErrors];

export type PostApiGhostWavByWavIdSkeletonResponses = {
    /**
     * Wav skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostWavByWavIdSkeletonResponse = PostApiGhostWavByWavIdSkeletonResponses[keyof PostApiGhostWavByWavIdSkeletonResponses];

export type PostApiGhostMusData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/mus';
};

export type PostApiGhostMusErrors = {
    /**
     * Available mus are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostMusError = PostApiGhostMusErrors[keyof PostApiGhostMusErrors];

export type PostApiGhostMusResponses = {
    /**
     * Available mus in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostMusResponse = PostApiGhostMusResponses[keyof PostApiGhostMusResponses];

export type PostApiGhostMusByMusIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Mus id
         */
        musId: MusMusId;
    };
    query?: never;
    url: '/api/ghost/mus/{musId}/skeleton';
};

export type PostApiGhostMusByMusIdSkeletonErrors = {
    /**
     * Mus is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostMusByMusIdSkeletonError = PostApiGhostMusByMusIdSkeletonErrors[keyof PostApiGhostMusByMusIdSkeletonErrors];

export type PostApiGhostMusByMusIdSkeletonResponses = {
    /**
     * Mus skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostMusByMusIdSkeletonResponse = PostApiGhostMusByMusIdSkeletonResponses[keyof PostApiGhostMusByMusIdSkeletonResponses];

export type PostApiGhostEffData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/eff';
};

export type PostApiGhostEffErrors = {
    /**
     * Available eff are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostEffError = PostApiGhostEffErrors[keyof PostApiGhostEffErrors];

export type PostApiGhostEffResponses = {
    /**
     * Available eff in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostEffResponse = PostApiGhostEffResponses[keyof PostApiGhostEffResponses];

export type PostApiGhostEffByEffIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Eff id
         */
        effId: EffEffId;
    };
    query?: never;
    url: '/api/ghost/eff/{effId}/skeleton';
};

export type PostApiGhostEffByEffIdSkeletonErrors = {
    /**
     * Eff is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostEffByEffIdSkeletonError = PostApiGhostEffByEffIdSkeletonErrors[keyof PostApiGhostEffByEffIdSkeletonErrors];

export type PostApiGhostEffByEffIdSkeletonResponses = {
    /**
     * Eff skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostEffByEffIdSkeletonResponse = PostApiGhostEffByEffIdSkeletonResponses[keyof PostApiGhostEffByEffIdSkeletonResponses];

export type PostApiGhostIdsData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/ids';
};

export type PostApiGhostIdsErrors = {
    /**
     * Available ids are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostIdsError = PostApiGhostIdsErrors[keyof PostApiGhostIdsErrors];

export type PostApiGhostIdsResponses = {
    /**
     * Available ids in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostIdsResponse = PostApiGhostIdsResponses[keyof PostApiGhostIdsResponses];

export type PostApiGhostIdsByIdsIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Ids id
         */
        idsId: IdsIdsId;
    };
    query?: never;
    url: '/api/ghost/ids/{idsId}/skeleton';
};

export type PostApiGhostIdsByIdsIdSkeletonErrors = {
    /**
     * Ids is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostIdsByIdsIdSkeletonError = PostApiGhostIdsByIdsIdSkeletonErrors[keyof PostApiGhostIdsByIdsIdSkeletonErrors];

export type PostApiGhostIdsByIdsIdSkeletonResponses = {
    /**
     * Ids skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostIdsByIdsIdSkeletonResponse = PostApiGhostIdsByIdsIdSkeletonResponses[keyof PostApiGhostIdsByIdsIdSkeletonResponses];

export type PostApiGhostIniData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/ini';
};

export type PostApiGhostIniErrors = {
    /**
     * Available ini are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostIniError = PostApiGhostIniErrors[keyof PostApiGhostIniErrors];

export type PostApiGhostIniResponses = {
    /**
     * Available ini in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostIniResponse = PostApiGhostIniResponses[keyof PostApiGhostIniResponses];

export type PostApiGhostIniByIniIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Ini id
         */
        iniId: IniIniId;
    };
    query?: never;
    url: '/api/ghost/ini/{iniId}/skeleton';
};

export type PostApiGhostIniByIniIdSkeletonErrors = {
    /**
     * Ini is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostIniByIniIdSkeletonError = PostApiGhostIniByIniIdSkeletonErrors[keyof PostApiGhostIniByIniIdSkeletonErrors];

export type PostApiGhostIniByIniIdSkeletonResponses = {
    /**
     * Ini skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostIniByIniIdSkeletonResponse = PostApiGhostIniByIniIdSkeletonResponses[keyof PostApiGhostIniByIniIdSkeletonResponses];

export type PostApiGhostAreData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/are';
};

export type PostApiGhostAreErrors = {
    /**
     * Available ares are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostAreError = PostApiGhostAreErrors[keyof PostApiGhostAreErrors];

export type PostApiGhostAreResponses = {
    /**
     * Available ares in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostAreResponse = PostApiGhostAreResponses[keyof PostApiGhostAreResponses];

export type PostApiGhostAreByAreIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Are id
         */
        areId: AreAreId;
    };
    query?: never;
    url: '/api/ghost/are/{areId}/skeleton';
};

export type PostApiGhostAreByAreIdSkeletonErrors = {
    /**
     * Are is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostAreByAreIdSkeletonError = PostApiGhostAreByAreIdSkeletonErrors[keyof PostApiGhostAreByAreIdSkeletonErrors];

export type PostApiGhostAreByAreIdSkeletonResponses = {
    /**
     * Are skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostAreByAreIdSkeletonResponse = PostApiGhostAreByAreIdSkeletonResponses[keyof PostApiGhostAreByAreIdSkeletonResponses];

export type PostApiGhostTwodaData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/twoda';
};

export type PostApiGhostTwodaErrors = {
    /**
     * Available 2da tables are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostTwodaError = PostApiGhostTwodaErrors[keyof PostApiGhostTwodaErrors];

export type PostApiGhostTwodaResponses = {
    /**
     * Available 2da tables in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostTwodaResponse = PostApiGhostTwodaResponses[keyof PostApiGhostTwodaResponses];

export type PostApiGhostTwodaByTwodaIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * 2da id
         */
        twodaId: TwodaTwodaId;
    };
    query?: never;
    url: '/api/ghost/twoda/{twodaId}/skeleton';
};

export type PostApiGhostTwodaByTwodaIdSkeletonErrors = {
    /**
     * 2da is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostTwodaByTwodaIdSkeletonError = PostApiGhostTwodaByTwodaIdSkeletonErrors[keyof PostApiGhostTwodaByTwodaIdSkeletonErrors];

export type PostApiGhostTwodaByTwodaIdSkeletonResponses = {
    /**
     * 2da skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostTwodaByTwodaIdSkeletonResponse = PostApiGhostTwodaByTwodaIdSkeletonResponses[keyof PostApiGhostTwodaByTwodaIdSkeletonResponses];

export type PostApiGhostSrcData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/src';
};

export type PostApiGhostSrcErrors = {
    /**
     * Available srcs are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostSrcError = PostApiGhostSrcErrors[keyof PostApiGhostSrcErrors];

export type PostApiGhostSrcResponses = {
    /**
     * Available srcs in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostSrcResponse = PostApiGhostSrcResponses[keyof PostApiGhostSrcResponses];

export type PostApiGhostSrcBySrcIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Src id
         */
        srcId: SrcSrcId;
    };
    query?: never;
    url: '/api/ghost/src/{srcId}/skeleton';
};

export type PostApiGhostSrcBySrcIdSkeletonErrors = {
    /**
     * Src is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostSrcBySrcIdSkeletonError = PostApiGhostSrcBySrcIdSkeletonErrors[keyof PostApiGhostSrcBySrcIdSkeletonErrors];

export type PostApiGhostSrcBySrcIdSkeletonResponses = {
    /**
     * Src skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostSrcBySrcIdSkeletonResponse = PostApiGhostSrcBySrcIdSkeletonResponses[keyof PostApiGhostSrcBySrcIdSkeletonResponses];

export type PostApiGhostSearchData = {
    body: {
        ghostDir: string;
        partialName: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/search';
};

export type PostApiGhostSearchErrors = {
    /**
     * Ghost directory is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostSearchError = PostApiGhostSearchErrors[keyof PostApiGhostSearchErrors];

export type PostApiGhostSearchResponses = {
    /**
     * Matching ghost files (max 20), sorted by id
     */
    200: Array<{
        type: 'acm' | 'are' | 'bam' | 'bcs' | 'bmp' | 'cre' | 'dlg' | 'eff' | 'ids' | 'ini' | 'itm' | 'mos' | 'mus' | 'pvrz' | 'src' | 'tis' | 'twoda' | 'wav' | 'wed';
        id: string;
    }>;
};

export type PostApiGhostSearchResponse = PostApiGhostSearchResponses[keyof PostApiGhostSearchResponses];

export type PostApiGhostTlkByGameLanguageData = {
    body: {
        ghostDir: string;
        tlkRefs: Array<number>;
    };
    path: {
        /**
         * Tlk language
         */
        gameLanguage: GameLanguage;
    };
    query?: never;
    url: '/api/ghost/tlk/{gameLanguage}';
};

export type PostApiGhostTlkByGameLanguageErrors = {
    /**
     * Cannot get tlk ref, see error code
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'TLK_NOT_FOUND' | 'TLK_REF_NOT_FOUND';
        };
    };
};

export type PostApiGhostTlkByGameLanguageError = PostApiGhostTlkByGameLanguageErrors[keyof PostApiGhostTlkByGameLanguageErrors];

export type PostApiGhostTlkByGameLanguageResponses = {
    /**
     * Translated tlk ref
     */
    200: {
        data: {
            content: Array<{
                ref: number;
                line: string;
            }>;
        };
    };
};

export type PostApiGhostTlkByGameLanguageResponse = PostApiGhostTlkByGameLanguageResponses[keyof PostApiGhostTlkByGameLanguageResponses];

export type GetApiMapCreToDlgsByCreIdData = {
    body?: never;
    path: {
        /**
         * Cre id
         */
        creId: CreToDlgsCreId;
    };
    query?: never;
    url: '/api/map/creToDlgs/{creId}';
};

export type GetApiMapCreToDlgsByCreIdErrors = {
    /**
     * Dlgs ids were not found for the cre id
     */
    404: {
        error: {
            message: string;
            code: 'DLGS_NOT_FOUND';
        };
    };
};

export type GetApiMapCreToDlgsByCreIdError = GetApiMapCreToDlgsByCreIdErrors[keyof GetApiMapCreToDlgsByCreIdErrors];

export type GetApiMapCreToDlgsByCreIdResponses = {
    /**
     * Dlgs ids
     */
    200: Array<string>;
};

export type GetApiMapCreToDlgsByCreIdResponse = GetApiMapCreToDlgsByCreIdResponses[keyof GetApiMapCreToDlgsByCreIdResponses];

export type GetApiMapDlgToCresByDlgIdData = {
    body?: never;
    path: {
        /**
         * Dlg id
         */
        dlgId: DlgToCreDlgId;
    };
    query?: never;
    url: '/api/map/dlgToCres/{dlgId}';
};

export type GetApiMapDlgToCresByDlgIdErrors = {
    /**
     * Cre id were not found for this dlg id
     */
    404: {
        error: {
            message: string;
            code: 'CRE_NOT_FOUND';
        };
    };
};

export type GetApiMapDlgToCresByDlgIdError = GetApiMapDlgToCresByDlgIdErrors[keyof GetApiMapDlgToCresByDlgIdErrors];

export type GetApiMapDlgToCresByDlgIdResponses = {
    /**
     * Cre id
     */
    200: Array<string>;
};

export type GetApiMapDlgToCresByDlgIdResponse = GetApiMapDlgToCresByDlgIdResponses[keyof GetApiMapDlgToCresByDlgIdResponses];

export type GetApiMapItmToDlgsByItmIdData = {
    body?: never;
    path: {
        /**
         * Itm id
         */
        itmId: ItmToDlgsItmId;
    };
    query?: never;
    url: '/api/map/itmToDlgs/{itmId}';
};

export type GetApiMapItmToDlgsByItmIdErrors = {
    /**
     * Dlgs ids were not found for the itm id
     */
    404: {
        error: {
            message: string;
            code: 'DLGS_NOT_FOUND';
        };
    };
};

export type GetApiMapItmToDlgsByItmIdError = GetApiMapItmToDlgsByItmIdErrors[keyof GetApiMapItmToDlgsByItmIdErrors];

export type GetApiMapItmToDlgsByItmIdResponses = {
    /**
     * Dlgs ids
     */
    200: Array<string>;
};

export type GetApiMapItmToDlgsByItmIdResponse = GetApiMapItmToDlgsByItmIdResponses[keyof GetApiMapItmToDlgsByItmIdResponses];

export type GetApiMapDlgToItmsByDlgIdData = {
    body?: never;
    path: {
        /**
         * Dlg id
         */
        dlgId: DlgToItmDlgId;
    };
    query?: never;
    url: '/api/map/dlgToItms/{dlgId}';
};

export type GetApiMapDlgToItmsByDlgIdErrors = {
    /**
     * Itm id were not found for this dlg id
     */
    404: {
        error: {
            message: string;
            code: 'ITM_NOT_FOUND';
        };
    };
};

export type GetApiMapDlgToItmsByDlgIdError = GetApiMapDlgToItmsByDlgIdErrors[keyof GetApiMapDlgToItmsByDlgIdErrors];

export type GetApiMapDlgToItmsByDlgIdResponses = {
    /**
     * Itm id
     */
    200: Array<string>;
};

export type GetApiMapDlgToItmsByDlgIdResponse = GetApiMapDlgToItmsByDlgIdResponses[keyof GetApiMapDlgToItmsByDlgIdResponses];

export type GetApiSettingsGhostDirData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/ghostDir';
};

export type GetApiSettingsGhostDirResponses = {
    /**
     * Current ghost directory path settings
     */
    200: {
        ghostDir: string;
    };
};

export type GetApiSettingsGhostDirResponse = GetApiSettingsGhostDirResponses[keyof GetApiSettingsGhostDirResponses];

export type PostApiSettingsGhostDirData = {
    body: {
        ghostDir: string;
    };
    path?: never;
    query?: never;
    url: '/api/settings/ghostDir';
};

export type PostApiSettingsGhostDirErrors = {
    /**
     * No such directory for ghost directory
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiSettingsGhostDirError = PostApiSettingsGhostDirErrors[keyof PostApiSettingsGhostDirErrors];

export type PostApiSettingsGhostDirResponses = {
    /**
     * Current ghost directory path settings
     */
    200: {
        ghostDir: string;
    };
};

export type PostApiSettingsGhostDirResponse = PostApiSettingsGhostDirResponses[keyof PostApiSettingsGhostDirResponses];

export type GetApiSettingsPrismDirData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/prismDir';
};

export type GetApiSettingsPrismDirResponses = {
    /**
     * Current prism directory path settings
     */
    200: {
        prismDir: string;
    };
};

export type GetApiSettingsPrismDirResponse = GetApiSettingsPrismDirResponses[keyof GetApiSettingsPrismDirResponses];

export type PostApiSettingsPrismDirData = {
    body: {
        prismDir: string;
    };
    path?: never;
    query?: never;
    url: '/api/settings/prismDir';
};

export type PostApiSettingsPrismDirErrors = {
    /**
     * No such directory for prism directory
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiSettingsPrismDirError = PostApiSettingsPrismDirErrors[keyof PostApiSettingsPrismDirErrors];

export type PostApiSettingsPrismDirResponses = {
    /**
     * Current prism directory path settings
     */
    200: {
        prismDir: string;
    };
};

export type PostApiSettingsPrismDirResponse = PostApiSettingsPrismDirResponses[keyof PostApiSettingsPrismDirResponses];

export type GetApiSettingsShellDirData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/shellDir';
};

export type GetApiSettingsShellDirResponses = {
    /**
     * Current shell directory path settings
     */
    200: {
        shellDir: string;
    };
};

export type GetApiSettingsShellDirResponse = GetApiSettingsShellDirResponses[keyof GetApiSettingsShellDirResponses];

export type PostApiSettingsShellDirData = {
    body: {
        shellDir: string;
    };
    path?: never;
    query?: never;
    url: '/api/settings/shellDir';
};

export type PostApiSettingsShellDirErrors = {
    /**
     * No such directory for shell directory
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiSettingsShellDirError = PostApiSettingsShellDirErrors[keyof PostApiSettingsShellDirErrors];

export type PostApiSettingsShellDirResponses = {
    /**
     * Current shell directory path settings
     */
    200: {
        shellDir: string;
    };
};

export type PostApiSettingsShellDirResponse = PostApiSettingsShellDirResponses[keyof PostApiSettingsShellDirResponses];
