// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3003' | (string & {});
};

export type DialogueId = string;

export const GameLanguage = {
    RU_RU: 'ru_RU',
    EN_US: 'en_US',
    CS_CZ: 'cs_CZ',
    DE_DE: 'de_DE',
    FR_FR: 'fr_FR',
    KO_KR: 'ko_KR',
    PL_PL: 'pl_PL'
} as const;

export type GameLanguage = typeof GameLanguage[keyof typeof GameLanguage];

export type CreatureId = string;

/**
 * Dialogue resource name
 */
export type DialogueId2 = DialogueId & unknown;

/**
 * Skeleton creature language
 */
export type GameLanguage2 = GameLanguage;

/**
 * Creature resource name
 */
export type CreatureId2 = CreatureId & unknown;

export type PostApiFsValidateChitinKeyPathData = {
    body: {
        weiduExePath: string;
        chitinKeyPath: string;
        gameLanguage: 'ru_RU' | 'en_US' | 'cs_CZ' | 'de_DE' | 'fr_FR' | 'ko_KR' | 'pl_PL';
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/chitinKeyPath';
};

export type PostApiFsValidateChitinKeyPathErrors = {
    /**
     * Game folder is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'NO_BIFFS';
        };
    };
};

export type PostApiFsValidateChitinKeyPathError = PostApiFsValidateChitinKeyPathErrors[keyof PostApiFsValidateChitinKeyPathErrors];

export type PostApiFsValidateChitinKeyPathResponses = {
    /**
     * How many biffs are found by weidu in the game folder
     */
    200: {
        data: {
            biffsCount: number;
        };
    };
};

export type PostApiFsValidateChitinKeyPathResponse = PostApiFsValidateChitinKeyPathResponses[keyof PostApiFsValidateChitinKeyPathResponses];

export type PostApiFsValidateGhostPathData = {
    body: {
        ghostPath: string;
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/ghostPath';
};

export type PostApiFsValidateGhostPathErrors = {
    /**
     * Ghost directory not found
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'DIRECTORY_NOT_EMPTY';
        };
    };
    /**
     * Ghost directory not empty
     */
    406: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'DIRECTORY_NOT_EMPTY';
        };
    };
};

export type PostApiFsValidateGhostPathError = PostApiFsValidateGhostPathErrors[keyof PostApiFsValidateGhostPathErrors];

export type PostApiFsValidateGhostPathResponses = {
    /**
     * Ghost is valid
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostApiFsValidateGhostPathResponse = PostApiFsValidateGhostPathResponses[keyof PostApiFsValidateGhostPathResponses];

export type PostApiFsValidateWeiduPathData = {
    body: {
        weiduExePath: string;
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/weiduPath';
};

export type PostApiFsValidateWeiduPathErrors = {
    /**
     * Weidu error
     */
    400: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'WEIDU_ERROR';
        };
    };
    /**
     * Weidu not found
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'WEIDU_ERROR';
        };
    };
};

export type PostApiFsValidateWeiduPathError = PostApiFsValidateWeiduPathErrors[keyof PostApiFsValidateWeiduPathErrors];

export type PostApiFsValidateWeiduPathResponses = {
    /**
     * Weidu.exe version
     */
    200: {
        data: {
            version: string;
        };
    };
};

export type PostApiFsValidateWeiduPathResponse = PostApiFsValidateWeiduPathResponses[keyof PostApiFsValidateWeiduPathResponses];

export type GetApiPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ping';
};

export type GetApiPingResponses = {
    /**
     * pong asclepius
     */
    200: 'pong asclepius';
};

export type GetApiPingResponse = GetApiPingResponses[keyof GetApiPingResponses];

export type PostApiGhostDialogueByDialogueIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Dialogue resource name
         */
        dialogueId: DialogueId & unknown;
    };
    query?: never;
    url: '/api/ghost/dialogue/{dialogueId}/skeleton';
};

export type PostApiGhostDialogueByDialogueIdSkeletonErrors = {
    /**
     * Dialogue skeleton is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostDialogueByDialogueIdSkeletonError = PostApiGhostDialogueByDialogueIdSkeletonErrors[keyof PostApiGhostDialogueByDialogueIdSkeletonErrors];

export type PostApiGhostDialogueByDialogueIdSkeletonResponses = {
    /**
     * Dialogue skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostDialogueByDialogueIdSkeletonResponse = PostApiGhostDialogueByDialogueIdSkeletonResponses[keyof PostApiGhostDialogueByDialogueIdSkeletonResponses];

export type PostApiGhostDialogueByDialogueIdByGameLanguageData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Dialogue resource name
         */
        dialogueId: DialogueId & unknown;
        /**
         * Skeleton creature language
         */
        gameLanguage: GameLanguage;
    };
    query?: never;
    url: '/api/ghost/dialogue/{dialogueId}/{gameLanguage}';
};

export type PostApiGhostDialogueByDialogueIdByGameLanguageErrors = {
    /**
     * Dialogue translation is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostDialogueByDialogueIdByGameLanguageError = PostApiGhostDialogueByDialogueIdByGameLanguageErrors[keyof PostApiGhostDialogueByDialogueIdByGameLanguageErrors];

export type PostApiGhostDialogueByDialogueIdByGameLanguageResponses = {
    /**
     * Dialogue translation content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostDialogueByDialogueIdByGameLanguageResponse = PostApiGhostDialogueByDialogueIdByGameLanguageResponses[keyof PostApiGhostDialogueByDialogueIdByGameLanguageResponses];

export type PostApiGhostDialogueData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/dialogue';
};

export type PostApiGhostDialogueErrors = {
    /**
     * Available dialogues are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostDialogueError = PostApiGhostDialogueErrors[keyof PostApiGhostDialogueErrors];

export type PostApiGhostDialogueResponses = {
    /**
     * Available dialogues in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostDialogueResponse = PostApiGhostDialogueResponses[keyof PostApiGhostDialogueResponses];

export type PostApiGhostCreatureByCreatureIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Creature resource name
         */
        creatureId: CreatureId & unknown;
    };
    query?: never;
    url: '/api/ghost/creature/{creatureId}/skeleton';
};

export type PostApiGhostCreatureByCreatureIdSkeletonErrors = {
    /**
     * Creature skeleton is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostCreatureByCreatureIdSkeletonError = PostApiGhostCreatureByCreatureIdSkeletonErrors[keyof PostApiGhostCreatureByCreatureIdSkeletonErrors];

export type PostApiGhostCreatureByCreatureIdSkeletonResponses = {
    /**
     * Creature skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostCreatureByCreatureIdSkeletonResponse = PostApiGhostCreatureByCreatureIdSkeletonResponses[keyof PostApiGhostCreatureByCreatureIdSkeletonResponses];

export type PostApiGhostCreatureByCreatureIdByGameLanguageData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Creature resource name
         */
        creatureId: CreatureId & unknown;
        /**
         * Skeleton creature language
         */
        gameLanguage: GameLanguage;
    };
    query?: never;
    url: '/api/ghost/creature/{creatureId}/{gameLanguage}';
};

export type PostApiGhostCreatureByCreatureIdByGameLanguageErrors = {
    /**
     * Creature translation is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostCreatureByCreatureIdByGameLanguageError = PostApiGhostCreatureByCreatureIdByGameLanguageErrors[keyof PostApiGhostCreatureByCreatureIdByGameLanguageErrors];

export type PostApiGhostCreatureByCreatureIdByGameLanguageResponses = {
    /**
     * Creature translation content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostCreatureByCreatureIdByGameLanguageResponse = PostApiGhostCreatureByCreatureIdByGameLanguageResponses[keyof PostApiGhostCreatureByCreatureIdByGameLanguageResponses];

export type PostApiGhostCreatureData = {
    body: {
        ghostDir: string;
        partialName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/ghost/creature';
};

export type PostApiGhostCreatureErrors = {
    /**
     * Available creatures are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiGhostCreatureError = PostApiGhostCreatureErrors[keyof PostApiGhostCreatureErrors];

export type PostApiGhostCreatureResponses = {
    /**
     * Available creatures in ghost format
     */
    200: Array<string>;
};

export type PostApiGhostCreatureResponse = PostApiGhostCreatureResponses[keyof PostApiGhostCreatureResponses];

export type GetApiMapCreatureToDialoguesByCreatureIdData = {
    body?: never;
    path: {
        /**
         * Creature resource name
         */
        creatureId: CreatureId & unknown;
    };
    query?: never;
    url: '/api/map/creatureToDialogues/{creatureId}';
};

export type GetApiMapCreatureToDialoguesByCreatureIdErrors = {
    /**
     * Dialogues resource names were not found for this creature
     */
    404: {
        error: {
            message: string;
            code: 'DIALOGUES_NOT_FOUND';
        };
    };
};

export type GetApiMapCreatureToDialoguesByCreatureIdError = GetApiMapCreatureToDialoguesByCreatureIdErrors[keyof GetApiMapCreatureToDialoguesByCreatureIdErrors];

export type GetApiMapCreatureToDialoguesByCreatureIdResponses = {
    /**
     * Dialogues resource names
     */
    200: Array<string>;
};

export type GetApiMapCreatureToDialoguesByCreatureIdResponse = GetApiMapCreatureToDialoguesByCreatureIdResponses[keyof GetApiMapCreatureToDialoguesByCreatureIdResponses];

export type GetApiMapDialogueToCreatureByDialogueIdData = {
    body?: never;
    path: {
        /**
         * Dialogue resource name
         */
        dialogueId: DialogueId & unknown;
    };
    query?: never;
    url: '/api/map/dialogueToCreature/{dialogueId}';
};

export type GetApiMapDialogueToCreatureByDialogueIdErrors = {
    /**
     * Creature resource name were not found for this dialogue
     */
    404: {
        error: {
            message: string;
            code: 'CREATURE_NOT_FOUND';
        };
    };
};

export type GetApiMapDialogueToCreatureByDialogueIdError = GetApiMapDialogueToCreatureByDialogueIdErrors[keyof GetApiMapDialogueToCreatureByDialogueIdErrors];

export type GetApiMapDialogueToCreatureByDialogueIdResponses = {
    /**
     * Creature resource name
     */
    200: string;
};

export type GetApiMapDialogueToCreatureByDialogueIdResponse = GetApiMapDialogueToCreatureByDialogueIdResponses[keyof GetApiMapDialogueToCreatureByDialogueIdResponses];
