/* Autogenerated file */

export type AlignmentId
  = | 'chaotic_evil'
    | 'chaotic_good'
    | 'chaotic_neutral'
    | 'lawful_evil'
    | 'lawful_good'
    | 'lawful_neutral'
    | 'neutral'
    | 'neutral_evil'
    | 'neutral_good'
    | 'none'
;
