/* Autogenerated file */

export type DoorId
  = | 'a1600d10'
    | 'ar0400d1'
    | 'ar0500d1'
    | 'ar0502d3'
    | 'ar0511d1'
    | 'ar1500d1'
    | 'ar1500d2'
    | 'ar702d01'
    | 'ar702d03'
    | 'fakedoor'
    | 'statue'
;
