/* Autogenerated file */

export type SpellId
  = | 'special_add_jumble_curse'
    | 'special_add_raise_dead'
    | 'special_add_sensory_touch'
    | 'special_add_stories_bones_tell'
    | 'special_remove_jumble_curse'
    | 'special_remove_sensory_touch'
    | 'wizard_ball_lightning'
;
