// This file is auto-generated by @hey-api/openapi-ts

export const dialogueIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'dmorte.dlg'
} as const;

export const gameLanguageSchema = {
    type: 'string',
    enum: [
        'ru_RU',
        'en_US',
        'cs_CZ',
        'de_DE',
        'fr_FR',
        'ko_KR',
        'pl_PL'
    ],
    example: 'ru_RU'
} as const;
