/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

export const dlg_dlgId_skeletonSchema = {
    type: 'string',
    minLength: 1,
    example: 'dmorte1.dlg'
} as const;

export const cre_creId_skeletonSchema = {
    type: 'string',
    minLength: 1,
    example: 'morte.cre'
} as const;

export const cre_creId_gameLanguageSchema = {
    type: 'string',
    minLength: 1,
    example: 'morte.cre'
} as const;

export const gameLanguageSchema = {
    type: 'string',
    enum: [
        'ru_RU',
        'en_US',
        'cs_CZ',
        'de_DE',
        'fr_FR',
        'ko_KR',
        'pl_PL'
    ],
    example: 'ru_RU'
} as const;

export const itm_itmId_skeletonSchema = {
    type: 'string',
    minLength: 1,
    example: 'charchrm.itm'
} as const;

export const itm_itmId_gameLanguageSchema = {
    type: 'string',
    minLength: 1,
    example: 'charchrm.itm'
} as const;

export const creToDlgs_creIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'morte.cre'
} as const;

export const dlgToCre_dlgIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'dmorte1.dlg'
} as const;

export const itmToDlgs_itmIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'cube.itm'
} as const;

export const dlgToItm_dlgIdSchema = {
    type: 'string',
    minLength: 1,
    example: 'dcube.dlg'
} as const;
