// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiPingData, GetApiPingResponses, PostFsValidateChitinKeyPathData, PostFsValidateChitinKeyPathErrors, PostFsValidateChitinKeyPathResponses, PostFsValidateWeiduPathData, PostFsValidateWeiduPathErrors, PostFsValidateWeiduPathResponses, PostGhostDialogueByDialogueIdByLanguageData, PostGhostDialogueByDialogueIdByLanguageErrors, PostGhostDialogueByDialogueIdByLanguageResponses, PostGhostDialogueByDialogueIdSkeletonData, PostGhostDialogueByDialogueIdSkeletonErrors, PostGhostDialogueByDialogueIdSkeletonResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Validates CHITIN.key folder as a game folder
 */
export const postFsValidateChitinKeyPath = <ThrowOnError extends boolean = false>(options: Options<PostFsValidateChitinKeyPathData, ThrowOnError>) => (options.client ?? client).post<PostFsValidateChitinKeyPathResponses, PostFsValidateChitinKeyPathErrors, ThrowOnError>({
    responseType: 'json',
    url: '/fs/validate/chitinKeyPath',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Validates weidu.exe access
 */
export const postFsValidateWeiduPath = <ThrowOnError extends boolean = false>(options: Options<PostFsValidateWeiduPathData, ThrowOnError>) => (options.client ?? client).post<PostFsValidateWeiduPathResponses, PostFsValidateWeiduPathErrors, ThrowOnError>({
    responseType: 'json',
    url: '/fs/validate/weiduPath',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Ping
 */
export const getApiPing = <ThrowOnError extends boolean = false>(options?: Options<GetApiPingData, ThrowOnError>) => (options?.client ?? client).get<GetApiPingResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/ping',
    ...options
});

/**
 * Get skeleton of the dialogue in ghost format
 */
export const postGhostDialogueByDialogueIdSkeleton = <ThrowOnError extends boolean = false>(options: Options<PostGhostDialogueByDialogueIdSkeletonData, ThrowOnError>) => (options.client ?? client).post<PostGhostDialogueByDialogueIdSkeletonResponses, PostGhostDialogueByDialogueIdSkeletonErrors, ThrowOnError>({
    responseType: 'json',
    url: '/ghost/dialogue/{dialogueId}/skeleton',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get translation of the dialogue in ghost format
 */
export const postGhostDialogueByDialogueIdByLanguage = <ThrowOnError extends boolean = false>(options: Options<PostGhostDialogueByDialogueIdByLanguageData, ThrowOnError>) => (options.client ?? client).post<PostGhostDialogueByDialogueIdByLanguageResponses, PostGhostDialogueByDialogueIdByLanguageErrors, ThrowOnError>({
    responseType: 'json',
    url: '/ghost/dialogue/{dialogueId}/{language}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
