/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiAssetsByFilePathData, GetApiAssetsByFilePathErrors, GetApiAssetsByFilePathResponses, GetApiFsGhostDirByFilePathData, GetApiFsGhostDirByFilePathErrors, GetApiFsGhostDirByFilePathResponses, GetApiFsPrismDirByFilePathData, GetApiFsPrismDirByFilePathErrors, GetApiFsPrismDirByFilePathResponses, GetApiFsShellDirByFilePathData, GetApiFsShellDirByFilePathErrors, GetApiFsShellDirByFilePathResponses, GetApiGhostByResourceTypeByResourceNameSkeletonData, GetApiGhostByResourceTypeByResourceNameSkeletonErrors, GetApiGhostByResourceTypeByResourceNameSkeletonResponses, GetApiGhostByResourceTypeData, GetApiGhostByResourceTypeErrors, GetApiGhostByResourceTypeResponses, GetApiGhostData, GetApiGhostErrors, GetApiGhostResponses, GetApiGhostTlkByGameLanguageData, GetApiGhostTlkByGameLanguageErrors, GetApiGhostTlkByGameLanguageResponses, GetApiMapCreToDlgsByCreIdData, GetApiMapCreToDlgsByCreIdErrors, GetApiMapCreToDlgsByCreIdResponses, GetApiMapDlgToCresByDlgIdData, GetApiMapDlgToCresByDlgIdErrors, GetApiMapDlgToCresByDlgIdResponses, GetApiMapDlgToItmsByDlgIdData, GetApiMapDlgToItmsByDlgIdErrors, GetApiMapDlgToItmsByDlgIdResponses, GetApiMapItmToDlgsByItmIdData, GetApiMapItmToDlgsByItmIdErrors, GetApiMapItmToDlgsByItmIdResponses, GetApiPathsData, GetApiPathsResponses, GetApiPingData, GetApiPingResponses, PostApiFsDownloadWeiduData, PostApiFsDownloadWeiduErrors, PostApiFsDownloadWeiduResponses, PostApiFsOpenDirData, PostApiFsOpenDirErrors, PostApiFsOpenDirResponses, PostApiFsValidateChitinKeyFileData, PostApiFsValidateChitinKeyFileErrors, PostApiFsValidateChitinKeyFileResponses, PostApiFsValidateGhostDirData, PostApiFsValidateGhostDirErrors, PostApiFsValidateGhostDirResponses, PostApiFsValidateModsDirData, PostApiFsValidateModsDirErrors, PostApiFsValidateModsDirResponses, PostApiFsValidateWeiduExeDirData, PostApiFsValidateWeiduExeDirErrors, PostApiFsValidateWeiduExeDirResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Validates CHITIN.key directory as a game directory
 */
export const postApiFsValidateChitinKeyFile = <ThrowOnError extends boolean = false>(options: Options<PostApiFsValidateChitinKeyFileData, ThrowOnError>) => (options.client ?? client).post<PostApiFsValidateChitinKeyFileResponses, PostApiFsValidateChitinKeyFileErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/fs/validate/chitinKeyFile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Validates the configured ghost directory
 */
export const postApiFsValidateGhostDir = <ThrowOnError extends boolean = false>(options?: Options<PostApiFsValidateGhostDirData, ThrowOnError>) => (options?.client ?? client).post<PostApiFsValidateGhostDirResponses, PostApiFsValidateGhostDirErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/fs/validate/ghostDir',
    ...options
});

/**
 * Validates the configured mods runtime directory
 */
export const postApiFsValidateModsDir = <ThrowOnError extends boolean = false>(options?: Options<PostApiFsValidateModsDirData, ThrowOnError>) => (options?.client ?? client).post<PostApiFsValidateModsDirResponses, PostApiFsValidateModsDirErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/fs/validate/modsDir',
    ...options
});

/**
 * Validates weidu.exe in the configured weidu directory
 */
export const postApiFsValidateWeiduExeDir = <ThrowOnError extends boolean = false>(options?: Options<PostApiFsValidateWeiduExeDirData, ThrowOnError>) => (options?.client ?? client).post<PostApiFsValidateWeiduExeDirResponses, PostApiFsValidateWeiduExeDirErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/fs/validate/weiduExeDir',
    ...options
});

/**
 * Downloads WeiDU from GitHub into planar-weidu and returns the binary path
 */
export const postApiFsDownloadWeidu = <ThrowOnError extends boolean = false>(options: Options<PostApiFsDownloadWeiduData, ThrowOnError>) => (options.client ?? client).post<PostApiFsDownloadWeiduResponses, PostApiFsDownloadWeiduErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/fs/download/weidu',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Opens a directory in the OS file manager on the asclepius host
 */
export const postApiFsOpenDir = <ThrowOnError extends boolean = false>(options: Options<PostApiFsOpenDirData, ThrowOnError>) => (options.client ?? client).post<PostApiFsOpenDirResponses, PostApiFsOpenDirErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/fs/openDir',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get file content from ghost directory by relative path
 */
export const getApiFsGhostDirByFilePath = <ThrowOnError extends boolean = false>(options: Options<GetApiFsGhostDirByFilePathData, ThrowOnError>) => (options.client ?? client).get<GetApiFsGhostDirByFilePathResponses, GetApiFsGhostDirByFilePathErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/fs/ghostDir/{filePath}',
    ...options
});

/**
 * Get file content from prism directory by relative path
 */
export const getApiFsPrismDirByFilePath = <ThrowOnError extends boolean = false>(options: Options<GetApiFsPrismDirByFilePathData, ThrowOnError>) => (options.client ?? client).get<GetApiFsPrismDirByFilePathResponses, GetApiFsPrismDirByFilePathErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/fs/prismDir/{filePath}',
    ...options
});

/**
 * Get file content from shell directory by relative path
 */
export const getApiFsShellDirByFilePath = <ThrowOnError extends boolean = false>(options: Options<GetApiFsShellDirByFilePathData, ThrowOnError>) => (options.client ?? client).get<GetApiFsShellDirByFilePathResponses, GetApiFsShellDirByFilePathErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/fs/shellDir/{filePath}',
    ...options
});

/**
 * Get file content from ghost assets directory by relative path
 */
export const getApiAssetsByFilePath = <ThrowOnError extends boolean = false>(options: Options<GetApiAssetsByFilePathData, ThrowOnError>) => (options.client ?? client).get<GetApiAssetsByFilePathResponses, GetApiAssetsByFilePathErrors, ThrowOnError>({
    responseType: 'blob',
    url: '/api/assets/{filePath}',
    ...options
});

/**
 * Ping
 */
export const getApiPing = <ThrowOnError extends boolean = false>(options?: Options<GetApiPingData, ThrowOnError>) => (options?.client ?? client).get<GetApiPingResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/ping',
    ...options
});

/**
 * Get translation of the tlk ref
 */
export const getApiGhostTlkByGameLanguage = <ThrowOnError extends boolean = false>(options: Options<GetApiGhostTlkByGameLanguageData, ThrowOnError>) => (options.client ?? client).get<GetApiGhostTlkByGameLanguageResponses, GetApiGhostTlkByGameLanguageErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/ghost/tlk/{gameLanguage}',
    ...options
});

/**
 * Search ghost skeleton filenames across workbench resource types. Empty query matches all, anyway - cap 20
 */
export const getApiGhost = <ThrowOnError extends boolean = false>(options?: Options<GetApiGhostData, ThrowOnError>) => (options?.client ?? client).get<GetApiGhostResponses, GetApiGhostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/ghost',
    ...options
});

/**
 * List ghost skeletons of a resource type
 */
export const getApiGhostByResourceType = <ThrowOnError extends boolean = false>(options: Options<GetApiGhostByResourceTypeData, ThrowOnError>) => (options.client ?? client).get<GetApiGhostByResourceTypeResponses, GetApiGhostByResourceTypeErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/ghost/{resourceType}',
    ...options
});

/**
 * Get skeleton of a ghost resource
 */
export const getApiGhostByResourceTypeByResourceNameSkeleton = <ThrowOnError extends boolean = false>(options: Options<GetApiGhostByResourceTypeByResourceNameSkeletonData, ThrowOnError>) => (options.client ?? client).get<GetApiGhostByResourceTypeByResourceNameSkeletonResponses, GetApiGhostByResourceTypeByResourceNameSkeletonErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/ghost/{resourceType}/{resourceName}/skeleton',
    ...options
});

/**
 * Get dlgs ids for the cre id
 */
export const getApiMapCreToDlgsByCreId = <ThrowOnError extends boolean = false>(options: Options<GetApiMapCreToDlgsByCreIdData, ThrowOnError>) => (options.client ?? client).get<GetApiMapCreToDlgsByCreIdResponses, GetApiMapCreToDlgsByCreIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/map/creToDlgs/{creId}',
    ...options
});

/**
 * Get cre id for the dlg id
 */
export const getApiMapDlgToCresByDlgId = <ThrowOnError extends boolean = false>(options: Options<GetApiMapDlgToCresByDlgIdData, ThrowOnError>) => (options.client ?? client).get<GetApiMapDlgToCresByDlgIdResponses, GetApiMapDlgToCresByDlgIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/map/dlgToCres/{dlgId}',
    ...options
});

/**
 * Get dlgs ids for the itm id
 */
export const getApiMapItmToDlgsByItmId = <ThrowOnError extends boolean = false>(options: Options<GetApiMapItmToDlgsByItmIdData, ThrowOnError>) => (options.client ?? client).get<GetApiMapItmToDlgsByItmIdResponses, GetApiMapItmToDlgsByItmIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/map/itmToDlgs/{itmId}',
    ...options
});

/**
 * Get itm id for the dlg id
 */
export const getApiMapDlgToItmsByDlgId = <ThrowOnError extends boolean = false>(options: Options<GetApiMapDlgToItmsByDlgIdData, ThrowOnError>) => (options.client ?? client).get<GetApiMapDlgToItmsByDlgIdResponses, GetApiMapDlgToItmsByDlgIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/map/dlgToItms/{dlgId}',
    ...options
});

/**
 * Returns frozen paths snapshot, loaded at process start
 */
export const getApiPaths = <ThrowOnError extends boolean = false>(options?: Options<GetApiPathsData, ThrowOnError>) => (options?.client ?? client).get<GetApiPathsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/paths',
    ...options
});
