// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3003' | (string & {});
};

export type DialogueId = string;

export const Language = { RU: 'ru', EN: 'en' } as const;

export type Language = typeof Language[keyof typeof Language];

/**
 * Skeleton dialogue id
 */
export type DialogueId2 = DialogueId & unknown;

/**
 * Skeleton dialogue language
 */
export type Language2 = Language;

export type PostApiFsValidateChitinKeyPathData = {
    body: {
        weiduExePath: string;
        chitinKeyPath: string;
        lang: 'ru' | 'en';
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/chitinKeyPath';
};

export type PostApiFsValidateChitinKeyPathErrors = {
    /**
     * Game folder is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'NO_BIFFS';
        };
    };
};

export type PostApiFsValidateChitinKeyPathError = PostApiFsValidateChitinKeyPathErrors[keyof PostApiFsValidateChitinKeyPathErrors];

export type PostApiFsValidateChitinKeyPathResponses = {
    /**
     * How many biffs are found by weidu in the game folder
     */
    200: {
        data: {
            biffsCount: number;
        };
    };
};

export type PostApiFsValidateChitinKeyPathResponse = PostApiFsValidateChitinKeyPathResponses[keyof PostApiFsValidateChitinKeyPathResponses];

export type PostApiFsValidateWeiduPathData = {
    body: {
        weiduExePath: string;
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/weiduPath';
};

export type PostApiFsValidateWeiduPathErrors = {
    /**
     * Weidu error
     */
    400: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'WEIDU_ERROR';
        };
    };
    /**
     * Weidu not found
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'WEIDU_ERROR';
        };
    };
};

export type PostApiFsValidateWeiduPathError = PostApiFsValidateWeiduPathErrors[keyof PostApiFsValidateWeiduPathErrors];

export type PostApiFsValidateWeiduPathResponses = {
    /**
     * Weidu.exe version
     */
    200: {
        data: {
            version: string;
        };
    };
};

export type PostApiFsValidateWeiduPathResponse = PostApiFsValidateWeiduPathResponses[keyof PostApiFsValidateWeiduPathResponses];

export type GetApiPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ping';
};

export type GetApiPingResponses = {
    /**
     * Pong
     */
    200: 'pong';
};

export type GetApiPingResponse = GetApiPingResponses[keyof GetApiPingResponses];

export type PostApiGhostDialogueByDialogueIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Skeleton dialogue id
         */
        dialogueId: DialogueId & unknown;
    };
    query?: never;
    url: '/api/ghost/dialogue/{dialogueId}/skeleton';
};

export type PostApiGhostDialogueByDialogueIdSkeletonErrors = {
    /**
     * Dialogue skeleton is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostDialogueByDialogueIdSkeletonError = PostApiGhostDialogueByDialogueIdSkeletonErrors[keyof PostApiGhostDialogueByDialogueIdSkeletonErrors];

export type PostApiGhostDialogueByDialogueIdSkeletonResponses = {
    /**
     * Dialogue skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostDialogueByDialogueIdSkeletonResponse = PostApiGhostDialogueByDialogueIdSkeletonResponses[keyof PostApiGhostDialogueByDialogueIdSkeletonResponses];

export type PostApiGhostDialogueByDialogueIdByLanguageData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Skeleton dialogue id
         */
        dialogueId: DialogueId & unknown;
        /**
         * Skeleton dialogue language
         */
        language: Language;
    };
    query?: never;
    url: '/api/ghost/dialogue/{dialogueId}/{language}';
};

export type PostApiGhostDialogueByDialogueIdByLanguageErrors = {
    /**
     * Dialogue translation is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostDialogueByDialogueIdByLanguageError = PostApiGhostDialogueByDialogueIdByLanguageErrors[keyof PostApiGhostDialogueByDialogueIdByLanguageErrors];

export type PostApiGhostDialogueByDialogueIdByLanguageResponses = {
    /**
     * Dialogue translation content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostDialogueByDialogueIdByLanguageResponse = PostApiGhostDialogueByDialogueIdByLanguageResponses[keyof PostApiGhostDialogueByDialogueIdByLanguageResponses];
