// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3003' | (string & {});
};

export type DialogueId = string;

export const GameLanguage = {
    RU_RU: 'ru_RU',
    EN_US: 'en_US',
    CS_CZ: 'cs_CZ',
    DE_DE: 'de_DE',
    FR_FR: 'fr_FR',
    KO_KR: 'ko_KR',
    PL_PL: 'pl_PL'
} as const;

export type GameLanguage = typeof GameLanguage[keyof typeof GameLanguage];

/**
 * Skeleton dialogue id
 */
export type DialogueId2 = DialogueId & unknown;

/**
 * Skeleton dialogue language
 */
export type GameLanguage2 = GameLanguage;

export type PostApiFsValidateChitinKeyPathData = {
    body: {
        weiduExePath: string;
        chitinKeyPath: string;
        gameLanguage: 'ru_RU' | 'en_US' | 'cs_CZ' | 'de_DE' | 'fr_FR' | 'ko_KR' | 'pl_PL';
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/chitinKeyPath';
};

export type PostApiFsValidateChitinKeyPathErrors = {
    /**
     * Game folder is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'NO_BIFFS';
        };
    };
};

export type PostApiFsValidateChitinKeyPathError = PostApiFsValidateChitinKeyPathErrors[keyof PostApiFsValidateChitinKeyPathErrors];

export type PostApiFsValidateChitinKeyPathResponses = {
    /**
     * How many biffs are found by weidu in the game folder
     */
    200: {
        data: {
            biffsCount: number;
        };
    };
};

export type PostApiFsValidateChitinKeyPathResponse = PostApiFsValidateChitinKeyPathResponses[keyof PostApiFsValidateChitinKeyPathResponses];

export type PostApiFsValidateGhostPathData = {
    body: {
        ghostPath: string;
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/ghostPath';
};

export type PostApiFsValidateGhostPathErrors = {
    /**
     * Ghost directory not found
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'DIRECTORY_NOT_EMPTY';
        };
    };
    /**
     * Ghost directory not empty
     */
    406: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'DIRECTORY_NOT_EMPTY';
        };
    };
};

export type PostApiFsValidateGhostPathError = PostApiFsValidateGhostPathErrors[keyof PostApiFsValidateGhostPathErrors];

export type PostApiFsValidateGhostPathResponses = {
    /**
     * Ghost is valid
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostApiFsValidateGhostPathResponse = PostApiFsValidateGhostPathResponses[keyof PostApiFsValidateGhostPathResponses];

export type PostApiFsValidateWeiduPathData = {
    body: {
        weiduExePath: string;
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/weiduPath';
};

export type PostApiFsValidateWeiduPathErrors = {
    /**
     * Weidu error
     */
    400: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'WEIDU_ERROR';
        };
    };
    /**
     * Weidu not found
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'WEIDU_ERROR';
        };
    };
};

export type PostApiFsValidateWeiduPathError = PostApiFsValidateWeiduPathErrors[keyof PostApiFsValidateWeiduPathErrors];

export type PostApiFsValidateWeiduPathResponses = {
    /**
     * Weidu.exe version
     */
    200: {
        data: {
            version: string;
        };
    };
};

export type PostApiFsValidateWeiduPathResponse = PostApiFsValidateWeiduPathResponses[keyof PostApiFsValidateWeiduPathResponses];

export type GetApiPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ping';
};

export type GetApiPingResponses = {
    /**
     * Pong
     */
    200: 'pong';
};

export type GetApiPingResponse = GetApiPingResponses[keyof GetApiPingResponses];

export type PostApiGhostDialogueByDialogueIdSkeletonData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Skeleton dialogue id
         */
        dialogueId: DialogueId & unknown;
    };
    query?: never;
    url: '/api/ghost/dialogue/{dialogueId}/skeleton';
};

export type PostApiGhostDialogueByDialogueIdSkeletonErrors = {
    /**
     * Dialogue skeleton is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostDialogueByDialogueIdSkeletonError = PostApiGhostDialogueByDialogueIdSkeletonErrors[keyof PostApiGhostDialogueByDialogueIdSkeletonErrors];

export type PostApiGhostDialogueByDialogueIdSkeletonResponses = {
    /**
     * Dialogue skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostDialogueByDialogueIdSkeletonResponse = PostApiGhostDialogueByDialogueIdSkeletonResponses[keyof PostApiGhostDialogueByDialogueIdSkeletonResponses];

export type PostApiGhostDialogueByDialogueIdByGameLanguageData = {
    body: {
        ghostDir: string;
    };
    path: {
        /**
         * Skeleton dialogue id
         */
        dialogueId: DialogueId & unknown;
        /**
         * Skeleton dialogue language
         */
        gameLanguage: GameLanguage;
    };
    query?: never;
    url: '/api/ghost/dialogue/{dialogueId}/{gameLanguage}';
};

export type PostApiGhostDialogueByDialogueIdByGameLanguageErrors = {
    /**
     * Dialogue translation is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type PostApiGhostDialogueByDialogueIdByGameLanguageError = PostApiGhostDialogueByDialogueIdByGameLanguageErrors[keyof PostApiGhostDialogueByDialogueIdByGameLanguageErrors];

export type PostApiGhostDialogueByDialogueIdByGameLanguageResponses = {
    /**
     * Dialogue translation content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type PostApiGhostDialogueByDialogueIdByGameLanguageResponse = PostApiGhostDialogueByDialogueIdByGameLanguageResponses[keyof PostApiGhostDialogueByDialogueIdByGameLanguageResponses];
