/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3003' | (string & {});
};

export type PostApiFsValidateChitinKeyFileData = {
    body: {
        chitinKeyFile: string;
        gameLanguage: 'ru_RU' | 'en_US' | 'cs_CZ' | 'de_DE' | 'fr_FR' | 'ko_KR' | 'pl_PL';
    };
    path?: never;
    query?: never;
    url: '/api/fs/validate/chitinKeyFile';
};

export type PostApiFsValidateChitinKeyFileErrors = {
    /**
     * Game directory is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'NO_BIFFS';
        };
    };
};

export type PostApiFsValidateChitinKeyFileError = PostApiFsValidateChitinKeyFileErrors[keyof PostApiFsValidateChitinKeyFileErrors];

export type PostApiFsValidateChitinKeyFileResponses = {
    /**
     * How many biffs are found by weidu in the game directory
     */
    200: {
        data: {
            biffsCount: number;
        };
    };
};

export type PostApiFsValidateChitinKeyFileResponse = PostApiFsValidateChitinKeyFileResponses[keyof PostApiFsValidateChitinKeyFileResponses];

export type PostApiFsValidateGhostDirData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/fs/validate/ghostDir';
};

export type PostApiFsValidateGhostDirErrors = {
    /**
     * Ghost directory not found
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'DIRECTORY_NOT_EMPTY';
        };
    };
    /**
     * Ghost directory not empty
     */
    406: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'DIRECTORY_NOT_EMPTY';
        };
    };
};

export type PostApiFsValidateGhostDirError = PostApiFsValidateGhostDirErrors[keyof PostApiFsValidateGhostDirErrors];

export type PostApiFsValidateGhostDirResponses = {
    /**
     * Ghost is valid
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostApiFsValidateGhostDirResponse = PostApiFsValidateGhostDirResponses[keyof PostApiFsValidateGhostDirResponses];

export type PostApiFsValidateModsDirData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/fs/validate/modsDir';
};

export type PostApiFsValidateModsDirErrors = {
    /**
     * Mods directory not found
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type PostApiFsValidateModsDirError = PostApiFsValidateModsDirErrors[keyof PostApiFsValidateModsDirErrors];

export type PostApiFsValidateModsDirResponses = {
    /**
     * Mods directory is valid
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostApiFsValidateModsDirResponse = PostApiFsValidateModsDirResponses[keyof PostApiFsValidateModsDirResponses];

export type PostApiFsValidateWeiduExeDirData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/fs/validate/weiduExeDir';
};

export type PostApiFsValidateWeiduExeDirErrors = {
    /**
     * Weidu error
     */
    400: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'WEIDU_ERROR';
        };
    };
    /**
     * Weidu not found
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'WEIDU_ERROR';
        };
    };
};

export type PostApiFsValidateWeiduExeDirError = PostApiFsValidateWeiduExeDirErrors[keyof PostApiFsValidateWeiduExeDirErrors];

export type PostApiFsValidateWeiduExeDirResponses = {
    /**
     * Weidu.exe version
     */
    200: {
        data: {
            version: string;
        };
    };
};

export type PostApiFsValidateWeiduExeDirResponse = PostApiFsValidateWeiduExeDirResponses[keyof PostApiFsValidateWeiduExeDirResponses];

export type PostApiFsDownloadWeiduData = {
    body: {
        platform: 'windows' | 'linux' | 'mac';
    };
    path?: never;
    query?: never;
    url: '/api/fs/download/weidu';
};

export type PostApiFsDownloadWeiduErrors = {
    /**
     * WeiDU binary not found in archive
     */
    404: {
        error: {
            message: string;
            code: 'DOWNLOAD_FAILED' | 'EXTRACT_FAILED' | 'BINARY_NOT_FOUND';
        };
    };
    /**
     * Failed to extract WeiDU
     */
    500: {
        error: {
            message: string;
            code: 'DOWNLOAD_FAILED' | 'EXTRACT_FAILED' | 'BINARY_NOT_FOUND';
        };
    };
    /**
     * Failed to download WeiDU
     */
    502: {
        error: {
            message: string;
            code: 'DOWNLOAD_FAILED' | 'EXTRACT_FAILED' | 'BINARY_NOT_FOUND';
        };
    };
};

export type PostApiFsDownloadWeiduError = PostApiFsDownloadWeiduErrors[keyof PostApiFsDownloadWeiduErrors];

export type PostApiFsDownloadWeiduResponses = {
    /**
     * Path to the WeiDU binary
     */
    200: {
        data: {
            weiduExeDir: string;
        };
    };
};

export type PostApiFsDownloadWeiduResponse = PostApiFsDownloadWeiduResponses[keyof PostApiFsDownloadWeiduResponses];

export type PostApiFsOpenDirData = {
    body: {
        dir: string;
    };
    path?: never;
    query?: never;
    url: '/api/fs/openDir';
};

export type PostApiFsOpenDirErrors = {
    /**
     * Path is not a directory
     */
    400: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'NOT_A_DIRECTORY' | 'OPEN_FAILED';
        };
    };
    /**
     * Directory not found
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'NOT_A_DIRECTORY' | 'OPEN_FAILED';
        };
    };
    /**
     * Failed to open directory
     */
    500: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND' | 'NOT_A_DIRECTORY' | 'OPEN_FAILED';
        };
    };
};

export type PostApiFsOpenDirError = PostApiFsOpenDirErrors[keyof PostApiFsOpenDirErrors];

export type PostApiFsOpenDirResponses = {
    /**
     * Directory opened
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostApiFsOpenDirResponse = PostApiFsOpenDirResponses[keyof PostApiFsOpenDirResponses];

export type GetApiFsGhostDirByFilePathData = {
    body?: never;
    path: {
        /**
         * Relative path to the file relative to ghost directory, can include lower slashes
         */
        filePath: string;
    };
    query?: never;
    url: '/api/fs/ghostDir/{filePath}';
};

export type GetApiFsGhostDirByFilePathErrors = {
    /**
     * Forbidden relative path in the ghost directory
     */
    403: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
    /**
     * No such file in the ghost directory
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
};

export type GetApiFsGhostDirByFilePathError = GetApiFsGhostDirByFilePathErrors[keyof GetApiFsGhostDirByFilePathErrors];

export type GetApiFsGhostDirByFilePathResponses = {
    /**
     * File content from ghost directory
     */
    200: string;
};

export type GetApiFsGhostDirByFilePathResponse = GetApiFsGhostDirByFilePathResponses[keyof GetApiFsGhostDirByFilePathResponses];

export type GetApiFsPrismDirByFilePathData = {
    body?: never;
    path: {
        /**
         * Relative path to the file relative to prism dist directory, can include lower slashes
         */
        filePath: string;
    };
    query?: never;
    url: '/api/fs/prismDir/{filePath}';
};

export type GetApiFsPrismDirByFilePathErrors = {
    /**
     * Forbidden relative path in the prism directory
     */
    403: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
    /**
     * No such file in the prism directory
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
};

export type GetApiFsPrismDirByFilePathError = GetApiFsPrismDirByFilePathErrors[keyof GetApiFsPrismDirByFilePathErrors];

export type GetApiFsPrismDirByFilePathResponses = {
    /**
     * File content from prism directory
     */
    200: string;
};

export type GetApiFsPrismDirByFilePathResponse = GetApiFsPrismDirByFilePathResponses[keyof GetApiFsPrismDirByFilePathResponses];

export type GetApiFsShellDirByFilePathData = {
    body?: never;
    path: {
        /**
         * Relative path to the file relative to shell dist directory, can include lower slashes
         */
        filePath: string;
    };
    query?: never;
    url: '/api/fs/shellDir/{filePath}';
};

export type GetApiFsShellDirByFilePathErrors = {
    /**
     * Forbidden relative path in the shell directory
     */
    403: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
    /**
     * No such file in the shell directory
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
};

export type GetApiFsShellDirByFilePathError = GetApiFsShellDirByFilePathErrors[keyof GetApiFsShellDirByFilePathErrors];

export type GetApiFsShellDirByFilePathResponses = {
    /**
     * File content from shell directory
     */
    200: string;
};

export type GetApiFsShellDirByFilePathResponse = GetApiFsShellDirByFilePathResponses[keyof GetApiFsShellDirByFilePathResponses];

export type GetApiAssetsByFilePathData = {
    body?: never;
    path: {
        /**
         * Relative path to the file in assets directory
         */
        filePath: string;
    };
    query?: never;
    url: '/api/assets/{filePath}';
};

export type GetApiAssetsByFilePathErrors = {
    /**
     * Forbidden relative path in the assets directory
     */
    403: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
    /**
     * No such file in the assets directory
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'DIRECTORY_TRAVERSE';
        };
    };
};

export type GetApiAssetsByFilePathError = GetApiAssetsByFilePathErrors[keyof GetApiAssetsByFilePathErrors];

export type GetApiAssetsByFilePathResponses = {
    /**
     * File content from assets directory
     */
    200: Blob | File;
};

export type GetApiAssetsByFilePathResponse = GetApiAssetsByFilePathResponses[keyof GetApiAssetsByFilePathResponses];

export type GetApiPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ping';
};

export type GetApiPingResponses = {
    /**
     * pong asclepius
     */
    200: 'pong asclepius';
};

export type GetApiPingResponse = GetApiPingResponses[keyof GetApiPingResponses];

export type GetApiGhostTlkByGameLanguageData = {
    body?: never;
    path: {
        gameLanguage: 'ru_RU' | 'en_US' | 'cs_CZ' | 'de_DE' | 'fr_FR' | 'ko_KR' | 'pl_PL';
    };
    query?: {
        tlkRefs?: Array<number | null> | null;
    };
    url: '/api/ghost/tlk/{gameLanguage}';
};

export type GetApiGhostTlkByGameLanguageErrors = {
    /**
     * Cannot get tlk ref, see error code
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND' | 'TLK_NOT_FOUND' | 'TLK_REF_NOT_FOUND';
        };
    };
};

export type GetApiGhostTlkByGameLanguageError = GetApiGhostTlkByGameLanguageErrors[keyof GetApiGhostTlkByGameLanguageErrors];

export type GetApiGhostTlkByGameLanguageResponses = {
    /**
     * Translated tlk ref
     */
    200: {
        data: {
            content: Array<{
                ref: number;
                line: string;
            }>;
        };
    };
};

export type GetApiGhostTlkByGameLanguageResponse = GetApiGhostTlkByGameLanguageResponses[keyof GetApiGhostTlkByGameLanguageResponses];

export type GetApiGhostData = {
    body?: never;
    path?: never;
    query?: {
        partialName?: string;
    };
    url: '/api/ghost';
};

export type GetApiGhostErrors = {
    /**
     * Ghost directory is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type GetApiGhostError = GetApiGhostErrors[keyof GetApiGhostErrors];

export type GetApiGhostResponses = {
    /**
     * Matching ghost files (max 20), sorted by id
     */
    200: Array<{
        type: 'acm' | 'are' | 'bam' | 'bcs' | 'bmp' | 'cre' | 'dlg' | 'eff' | 'ids' | 'ini' | 'itm' | 'mos' | 'mus' | 'pvrz' | 'src' | 'tis' | 'twoda' | 'wav' | 'wed';
        id: string;
    }>;
};

export type GetApiGhostResponse = GetApiGhostResponses[keyof GetApiGhostResponses];

export type GetApiGhostByResourceTypeData = {
    body?: never;
    path: {
        resourceType: 'acm' | 'are' | 'bam' | 'bcs' | 'bmp' | 'cre' | 'dlg' | 'eff' | 'ids' | 'ini' | 'itm' | 'mos' | 'mus' | 'pvrz' | 'src' | 'tis' | 'twoda' | 'wav' | 'wed';
    };
    query?: {
        partialName?: string;
    };
    url: '/api/ghost/{resourceType}';
};

export type GetApiGhostByResourceTypeErrors = {
    /**
     * Unknown resourceType
     */
    400: unknown;
    /**
     * Available resources are not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'DIRECTORY_NOT_FOUND';
        };
    };
};

export type GetApiGhostByResourceTypeError = GetApiGhostByResourceTypeErrors[keyof GetApiGhostByResourceTypeErrors];

export type GetApiGhostByResourceTypeResponses = {
    /**
     * Available resources in ghost format
     */
    200: Array<string>;
};

export type GetApiGhostByResourceTypeResponse = GetApiGhostByResourceTypeResponses[keyof GetApiGhostByResourceTypeResponses];

export type GetApiGhostByResourceTypeByResourceNameSkeletonData = {
    body?: never;
    path: {
        resourceType: 'acm' | 'are' | 'bam' | 'bcs' | 'bmp' | 'cre' | 'dlg' | 'eff' | 'ids' | 'ini' | 'itm' | 'mos' | 'mus' | 'pvrz' | 'src' | 'tis' | 'twoda' | 'wav' | 'wed';
        resourceName: string;
    };
    query?: never;
    url: '/api/ghost/{resourceType}/{resourceName}/skeleton';
};

export type GetApiGhostByResourceTypeByResourceNameSkeletonErrors = {
    /**
     * Unknown resourceType
     */
    400: unknown;
    /**
     * Resource is not found by this path
     */
    404: {
        error: {
            message: string;
            code: 'FILE_NOT_FOUND';
        };
    };
};

export type GetApiGhostByResourceTypeByResourceNameSkeletonError = GetApiGhostByResourceTypeByResourceNameSkeletonErrors[keyof GetApiGhostByResourceTypeByResourceNameSkeletonErrors];

export type GetApiGhostByResourceTypeByResourceNameSkeletonResponses = {
    /**
     * Skeleton content in ghost format
     */
    200: {
        data: {
            content: string;
        };
    };
};

export type GetApiGhostByResourceTypeByResourceNameSkeletonResponse = GetApiGhostByResourceTypeByResourceNameSkeletonResponses[keyof GetApiGhostByResourceTypeByResourceNameSkeletonResponses];

export type GetApiMapCreToDlgsByCreIdData = {
    body?: never;
    path: {
        creId: string;
    };
    query?: never;
    url: '/api/map/creToDlgs/{creId}';
};

export type GetApiMapCreToDlgsByCreIdErrors = {
    /**
     * Dlgs ids were not found for the cre id
     */
    404: {
        error: {
            message: string;
            code: 'DLGS_NOT_FOUND';
        };
    };
};

export type GetApiMapCreToDlgsByCreIdError = GetApiMapCreToDlgsByCreIdErrors[keyof GetApiMapCreToDlgsByCreIdErrors];

export type GetApiMapCreToDlgsByCreIdResponses = {
    /**
     * Dlgs ids
     */
    200: Array<string>;
};

export type GetApiMapCreToDlgsByCreIdResponse = GetApiMapCreToDlgsByCreIdResponses[keyof GetApiMapCreToDlgsByCreIdResponses];

export type GetApiMapDlgToCresByDlgIdData = {
    body?: never;
    path: {
        dlgId: string;
    };
    query?: never;
    url: '/api/map/dlgToCres/{dlgId}';
};

export type GetApiMapDlgToCresByDlgIdErrors = {
    /**
     * Cre id were not found for this dlg id
     */
    404: {
        error: {
            message: string;
            code: 'CRE_NOT_FOUND';
        };
    };
};

export type GetApiMapDlgToCresByDlgIdError = GetApiMapDlgToCresByDlgIdErrors[keyof GetApiMapDlgToCresByDlgIdErrors];

export type GetApiMapDlgToCresByDlgIdResponses = {
    /**
     * Cre id
     */
    200: Array<string>;
};

export type GetApiMapDlgToCresByDlgIdResponse = GetApiMapDlgToCresByDlgIdResponses[keyof GetApiMapDlgToCresByDlgIdResponses];

export type GetApiMapItmToDlgsByItmIdData = {
    body?: never;
    path: {
        itmId: string;
    };
    query?: never;
    url: '/api/map/itmToDlgs/{itmId}';
};

export type GetApiMapItmToDlgsByItmIdErrors = {
    /**
     * Dlgs ids were not found for the itm id
     */
    404: {
        error: {
            message: string;
            code: 'DLGS_NOT_FOUND';
        };
    };
};

export type GetApiMapItmToDlgsByItmIdError = GetApiMapItmToDlgsByItmIdErrors[keyof GetApiMapItmToDlgsByItmIdErrors];

export type GetApiMapItmToDlgsByItmIdResponses = {
    /**
     * Dlgs ids
     */
    200: Array<string>;
};

export type GetApiMapItmToDlgsByItmIdResponse = GetApiMapItmToDlgsByItmIdResponses[keyof GetApiMapItmToDlgsByItmIdResponses];

export type GetApiMapDlgToItmsByDlgIdData = {
    body?: never;
    path: {
        dlgId: string;
    };
    query?: never;
    url: '/api/map/dlgToItms/{dlgId}';
};

export type GetApiMapDlgToItmsByDlgIdErrors = {
    /**
     * Itm id were not found for this dlg id
     */
    404: {
        error: {
            message: string;
            code: 'ITM_NOT_FOUND';
        };
    };
};

export type GetApiMapDlgToItmsByDlgIdError = GetApiMapDlgToItmsByDlgIdErrors[keyof GetApiMapDlgToItmsByDlgIdErrors];

export type GetApiMapDlgToItmsByDlgIdResponses = {
    /**
     * Itm id
     */
    200: Array<string>;
};

export type GetApiMapDlgToItmsByDlgIdResponse = GetApiMapDlgToItmsByDlgIdResponses[keyof GetApiMapDlgToItmsByDlgIdResponses];

export type GetApiPathsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/paths';
};

export type GetApiPathsResponses = {
    /**
     * Resolved directories
     */
    200: {
        asclepius: {
            root: string;
            dist: string;
            defaultsJson: string;
        };
        repository: {
            root: string;
        };
        daemon: {
            root: string;
            dist: string;
        };
        ghost: {
            root: string;
        };
        kernel: {
            root: string;
            dist: string;
        };
        mods: {
            root: string;
            dist: string;
        };
        modsRuntime: {
            root: string;
        };
        prism: {
            root: string;
            dist: string;
            defaultsJson: string;
        };
        shared: {
            root: string;
            dist: string;
        };
        shell: {
            root: string;
            dist: string;
        };
        weidu: {
            root: string;
            exe: string;
        };
    };
};

export type GetApiPathsResponse = GetApiPathsResponses[keyof GetApiPathsResponses];
