/* Autogenerated file */

export type ScriptId
  = | 'mdkannah'
    | 'mdkgrace'
    | 'mdktno'
    | 'pcannah'
    | 'pcdakkon'
    | 'pcgrace'
    | 'pcignus'
    | 'pcmorte'
    | 'pcnordom'
    | 'pcvhail'
;
