/* Autogenerated file */

export type StatId
  = | 'armorclass'
    | 'chr'
    | 'con'
    | 'damagebonus'
    | 'dex'
    | 'int'
    | 'level'
    | 'lockpicking'
    | 'luck'
    | 'maxhitpoints'
    | 'pickpocket'
    | 'resistfire'
    | 'resistmagicfire'
    | 'stealth'
    | 'str'
    | 'traps'
    | 'wis'
;
