export type Direction
  = | '0=south'
    | '1=south-south-west'
    | '2=south-west'
    | '3=south-west-west'
    | '4=west'
    | '5=north-west-west'
    | '6=north-west'
    | '7=north-north-west'
    | '8=north'
    | '9=north-north-east'
    | '10=north-east'
    | '11=north-east-east'
    | '12=east'
    | '13=south-east-east'
    | '14=south-east'
    | '15=south-south-east'
;
