import type { Direction, Maybe } from '@planar/shared';
import type { RawIniCreatureIniPointSelect } from './parsePointSelectV1.types.js';
import type { RawIniCreatureIniScopedVariable } from './parseScopedVariableV1.types.js';
import type { RawIniCreatureIniSpawnPoint } from './parseSpawnPointsV1.types.js';
import type { RawIniCreatureIniSpecArea } from './parseSpecAreaV1.types.js';
import type { RawIniCreatureIniSpec } from './parseSpecV1.types.js';
import type { RawIniCreatureIniSpecVarOperation } from './parseSpecVarOperationV1.types.js';

export type RawIniCreatureIniSection = Readonly<{
  name: string;
  specVar: Maybe<RawIniCreatureIniScopedVariable>;
  spec: string | RawIniCreatureIniSpec;
  specArea: Maybe<RawIniCreatureIniSpecArea>;
  specQty: number;
  specVarInc?: Maybe<number>;
  specVarValue?: Maybe<number>;
  specVarOperation?: Maybe<RawIniCreatureIniSpecVarOperation>;
  areaDiff1?: Maybe<boolean>;
  areaDiff2?: Maybe<boolean>;
  areaDiff3?: Maybe<boolean>;
  creFile: string;
  createQty?: Maybe<number>;
  scriptName?: Maybe<string>;
  aiEa?: Maybe<number>;
  aiGeneral?: Maybe<number>;
  aiRace?: Maybe<number>;
  aiClass?: Maybe<number>;
  aiGender?: Maybe<number>;
  aiSpecifics?: Maybe<number>;
  aiAlignment?: Maybe<number>;
  aiFaction?: Maybe<number>;
  aiTeam?: Maybe<string | number>; // TODO [snow]: what type is it?
  scriptOverride?: Maybe<string>;
  scriptClass?: Maybe<string>;
  scriptRace?: Maybe<string>;
  scriptGeneral?: Maybe<string>;
  scriptDefault?: Maybe<string>;
  scriptArea?: Maybe<string>;
  scriptSpecifics?: Maybe<string>;
  scriptSpecial1?: Maybe<string>;
  scriptTeam?: Maybe<string>;
  scriptSpecial2?: Maybe<string>;
  scriptCombat?: Maybe<string>;
  scriptSpecial3?: Maybe<string>;
  scriptMovement?: Maybe<string>;
  dialog?: Maybe<string>;
  goodMod?: Maybe<number>;
  lawMod?: Maybe<number>;
  ladyMod?: Maybe<number>;
  murderMod?: Maybe<number>;
  deathScriptname?: Maybe<boolean>;
  deathFaction?: Maybe<boolean>;
  deathTeam?: Maybe<boolean>;
  spawnPoint?: Maybe<RawIniCreatureIniSpawnPoint[]>;
  pointSelect: Maybe<RawIniCreatureIniPointSelect>;
  pointSelectVar?: Maybe<RawIniCreatureIniScopedVariable>;
  facing?: Maybe<Direction>;
  ignoreCanSee?: Maybe<boolean>;
  checkCrowd?: Maybe<boolean>;
  findSafestPoint?: boolean;
  saveSelectedPoint?: Maybe<RawIniCreatureIniScopedVariable>;
  saveSelectedFacing?: Maybe<RawIniCreatureIniScopedVariable>;
  spawnPointGlobal?: Maybe<RawIniCreatureIniScopedVariable>;
  spawnFacingGlobal?: Maybe<RawIniCreatureIniScopedVariable>;
  incSpawnPointIndex?: Maybe<boolean>;
  holdSelectedPointKey?: Maybe<boolean>;
  checkByViewPort?: Maybe<boolean>;
  doNotSpawn?: Maybe<boolean>;
  autoBuddy?: Maybe<boolean>;
  timeOfDay?: Maybe<string>;
  disableRenderer?: Maybe<boolean>;
}>;
