import type { Direction } from './parseDirectionV1.types.js';
import type { CreatureIniPointSelect } from './parsePointSelectV1.types.js';
import type { CreatureIniScopedVariable } from './parseScopedVariableV1.types.js';
import type { CreatureIniSpawnPoint } from './parseSpawnPointsV1.types.js';
import type { CreatureIniSpecArea } from './parseSpecAreaV1.types.js';
import type { CreatureIniSpec } from './parseSpecV1.types.js';
import type { CreatureIniSpecVarOperation } from './parseSpecVarOperationV1.types.js';

export type CreatureIniSection = Readonly<{
  name: string;
  specVar: CreatureIniScopedVariable;
  spec: string | CreatureIniSpec;
  specArea: CreatureIniSpecArea;
  specQty: number;
  specVarInc: number;
  specVarValue: number;
  specVarOperation: CreatureIniSpecVarOperation;
  areaDiff1: boolean;
  areaDiff2: boolean;
  areaDiff3: boolean;
  creFile: string;
  createQty: number;
  scriptName: string;
  aiEa: number;
  aiGeneral: number;
  aiRace: number;
  aiClass: number;
  aiGender: number;
  aiSpecifics: number;
  aiAlignment: number;
  aiFaction: number;
  aiTeam: string | number;
  scriptOverride: string;
  scriptClass: string;
  scriptRace: string;
  scriptGeneral: string;
  scriptDefault: string;
  scriptArea: string;
  scriptSpecifics: string;
  scriptSpecial1: string;
  scriptTeam: string;
  scriptSpecial2: string;
  scriptCombat: string;
  scriptSpecial3: string;
  scriptMovement: string;
  dialog: string;
  goodMod: number;
  lawMod: number;
  ladyMod: number;
  murderMod: number;
  deathScriptname: boolean;
  deathFaction: boolean;
  deathTeam: boolean;
  spawnPoint: CreatureIniSpawnPoint[];
  pointSelect: CreatureIniPointSelect;
  pointSelectVar: CreatureIniScopedVariable;
  facing: Direction;
  ignoreCanSee: boolean;
  checkCrowd: boolean;
  findSafestPoint: boolean;
  saveSelectedPoint: CreatureIniScopedVariable;
  saveSelectedFacing: CreatureIniScopedVariable;
  spawnPointGlobal: CreatureIniScopedVariable;
  spawnFacingGlobal: CreatureIniScopedVariable;
  incSpawnPointIndex: boolean;
  holdSelectedPointKey: boolean;
  checkByViewPort: boolean;
  doNotSpawn: boolean;
  autoBuddy: boolean;
  timeOfDay: string;
  disableRenderer: boolean;
}>;
