import type { Maybe } from '../maybe.js';
import type { AlignmentId } from './enums/alignment.ts';
import type { ClassId } from './enums/class.ts';
import type { DoorId } from './enums/door.ts';
import type { EnvId } from './enums/env.ts';
import type { ItemId } from './enums/item.ts';
import type { JournalId } from './enums/journal.ts';
import type { JournalTypeId } from './enums/journalType.ts';
import type { LocationId } from './enums/location.ts';
import type { WhoId } from './enums/who.ts';
import type { SceneId } from './enums/scene.ts';
import type { SoundId } from './enums/sound.ts';
import type { StatId } from './enums/stat.ts';
import type { NumberVariableId, BooleanVariableId } from './enums/variable.ts';
import type { ScriptId } from './enums/script.ts';
import type { MovieId } from './enums/movie.ts';
import type { TimeMeasureId } from './enums/timeMeasure.ts';
import type { SpellId } from './enums/spell.ts';
import type { SlotId } from './enums/slot.ts';
import type { TriggerId } from './enums/trigger.ts';
import type { PortalId } from './enums/portal.js';
import type { AnimationId } from './enums/animation.js';
import type { ScriptLevelId } from './enums/scriptLevel.js';
import type { KeyId } from './enums/key.js';
import type { ProficiencyId } from './enums/proficiency.js';
import type { TimerId } from './enums/timer.js';
import type { DisguiseId } from './enums/disguise.js';
import type { MessageId } from './enums/message.js';
import type { Direction } from '../direction.js';

export type DialogueLogic = Readonly<{
  getValue: (args: Readonly<{ variableId: NumberVariableId | BooleanVariableId; envId?: Maybe<EnvId> }>) => number;
  setValue: (args: Readonly<{ variableId: NumberVariableId | BooleanVariableId; envId?: Maybe<EnvId>; amount: number }>) => number;
  increment: (args: Readonly<{ variableId: NumberVariableId; envId?: Maybe<EnvId>; onceKey?: Maybe<KeyId>; amount: number }>) => number;
  setJournal: (journalId: JournalId) => void;
  isNpcInParty: (whoId: WhoId) => boolean;
  isNearbyDialog: (whoId: WhoId) => boolean;
  changeMorale: (args: Readonly<{ whoId: WhoId; amount: number }>) => void;
  isNpcDead: (whoId: WhoId) => boolean;
  createItem: (args: Readonly<{ itemId: ItemId; whoId?: Maybe<WhoId>; amount: number; identified: boolean; slotId: SlotId }>) => void;
  giveItem: (args: Readonly<{ itemId: ItemId; whoId: WhoId }>) => void;
  takeItem: (args: Readonly<{ itemId: ItemId; whoId: WhoId }>) => void;
  takePartyItems: (args: Readonly<{ itemId: ItemId; amount: number | 'stack' }>) => void;
  countPartyItem: (itemId: ItemId) => number;
  hasItem: (args: Readonly<{ itemId: ItemId; whoId: WhoId }>) => boolean;
  destroyItem: (args: Readonly<{ itemId: ItemId; whoId: WhoId; all?: Maybe<boolean> }>) => void;
  getNpcStat: (args: Readonly<{ whoId: WhoId; statId: StatId }>) => number;
  changeNpcStat: (args: Readonly<{ whoId: WhoId; statId: StatId; amount: number }>) => number;
  setNpcStat: (args: Readonly<{ whoId: WhoId; statId: StatId; amount: number }>) => number;
  attack: (args: Readonly<{ targetId: WhoId; whoId?: Maybe<WhoId>; force?: Maybe<boolean> }>) => void;
  startCutScene: (args: Readonly<{ sceneId: SceneId; checkConditions?: Maybe<boolean> }>) => void;
  fullHeal: (whoId: WhoId) => void;
  addExp: (args: Readonly<{ amount: number; whoId: WhoId }>) => void;
  changeGold: (args: Readonly<{ amount: number; operation: 'take' | 'destroy' | 'give'; force?: Maybe<boolean> }>) => number;
  getGold: () => number;
  playSound: (args: Readonly<{ soundId: SoundId; notRanged?: Maybe<boolean> }>) => void;
  enemy: () => void;
  getTimesTalkedToNpc: () => number;
  setTimesTalkedToNpc: (amount: number) => number;
  talk: (whoId: WhoId) => void;
  exists: (whoId: WhoId) => boolean;
  transformItem: (args: Readonly<{ fromItemId: ItemId; toItemId: ItemId; targetId: WhoId; charge1?: Maybe<number>; charge2?: Maybe<number>; charge3?: Maybe<number> }>) => void;
  getAlignment: (whoId: WhoId) => AlignmentId;
  generateModronMaze: () => void;
  countPartyMembers: () => number;
  setPortalCursor: (args: Readonly<{ locationId: LocationId; portalId: PortalId; reset: boolean }>) => void;
  trade: (args: Readonly<{ shopId: WhoId; customerId: WhoId }>) => void;
  getClass: (whoId: WhoId) => ClassId;
  setNamelessClass: (classId: ClassId) => void;
  setAnimation: (args: Readonly<{ whoId: WhoId; animationId: AnimationId }>) => void;
  showFloatingRebusAbove: (whoId: WhoId) => void;
  destroyCreature: (whoId: WhoId) => void;
  deactivate: (whoId: WhoId) => void;
  fadeColor: (args: Readonly<{ operation: 'to' | 'from'; x: number; y: number; unknown: number }>) => void;
  wait: (seconds: number) => void;
  kill: (whoId: WhoId) => void;
  help: () => void;
  playAnimation: (args: Readonly<{ animationId: AnimationId; x: number; y: number; blendingMode: number }>) => void;
  rest: (args: Readonly<{ gold: number; hpBonus: number; disableMoving: boolean }>) => void;
  teleportParty: (args: Readonly<{ locationId: LocationId; x: number; y: number; face: number }>) => void;
  changeScript: (args: Readonly<{ whoId: WhoId; scriptId: ScriptId; scriptLevelId: ScriptLevelId }>) => void;
  disableScript: (args: Readonly<{ whoId: WhoId; scriptLevelId: ScriptLevelId }>) => void;
  joinParty: (args: Readonly<{ whoId: WhoId; again?: Maybe<boolean>; joinGroup?: Maybe<boolean> }>) => void;
  turnKeyInDoor: (args: Readonly<{ doorId: DoorId; isLocked: boolean }>) => void;
  openDoor: (doorId: DoorId) => void;
  getLastNpcTalkedTo: () => WhoId;
  leaveParty: () => void;
  startCutsceneMode: () => void;
  startMovie: (movieId: MovieId) => void;
  runAway: (args: Readonly<{ whoId: WhoId; time: number; timeMeasureId: TimeMeasureId; noAttack: boolean }>) => void;
  clearActions: (whoId: WhoId) => void;
  roll: (max: number) => number;
  applySpell: (args: Readonly<{ whoId: WhoId; spellId: SpellId }>) => void;
  damageBy: (args: Readonly<{ whoId: WhoId; amount: number }>) => void;
  damageTo: (args: Readonly<{ whoId: WhoId; amount: number }>) => void;
  getHp: (whoId: WhoId) => number;
  changeWeaponProficiency: (args: Readonly<{ whoId: WhoId; slotId: SlotId; amount: number }>) => void;
  changeExtraProficiency: (args: Readonly<{ whoId: WhoId; amount: number }>) => void;
  escapeArea: () => void;
  createCreatureNearTo: (args: Readonly<{ creatureWhoId: WhoId; nearToWhoId: WhoId }>) => void;
  creatureInLocation: (args: Readonly<{ creatureWhoId: WhoId; location: LocationId }>) => boolean;
  changeTrigger: (args: Readonly<{ triggerId: TriggerId; active: boolean }>) => void;
  faceobject: (args: Readonly<{ whoId: WhoId; to: WhoId }>) => void;
  getProficiency: (args: Readonly<{ whoId: WhoId; proficiency: ProficiencyId }>) => number;
  getExtraProficiencyPoints: (whoId: WhoId) => number;
  countEnemiesInRange: (range: number) => number;
  dropInventory: () => void;
  quitGame: (args: Readonly<{ arg1: string; arg2: number; arg3: number }>) => void;
  sinisterPoof: (args: Readonly<{ poof: string; x: number; y: number; value: number; sticky: false }> | Readonly<{ poof: string; whoId: WhoId; value: number; sticky: true }>) => void;
  checkBit: (args: Readonly<{ variable: NumberVariableId | BooleanVariableId; env: EnvId; bit: string }>) => boolean;
  setBit: (args: Readonly<{ variable: NumberVariableId | BooleanVariableId; env: EnvId; bit: string }>) => void;
  getHpPercent: (whoId: WhoId) => number;
  setTimer: (args: Readonly<{ timer: TimerId; env: EnvId; seconds: number }>) => void;
  timerExpired: (args: Readonly<{ timer: TimerId; env: EnvId }>) => boolean;
  setRandomValue: (args: Readonly<{ variable: NumberVariableId; env: EnvId; from: number; to: number; inclucive: boolean }>) => boolean; // return boolean for backward compatibility
  clearAllActions: (whoId: WhoId) => void;
  polymorph: (args: Readonly<{ whoId: WhoId; target: string }>) => void;
  sleep: (seconds: number) => void;
  getClassLevel: (args: Readonly<{ whoId: WhoId; classId: ClassId }>) => number;
  moveCamera: (args: Readonly<{ x: number; y: number; animationTime: TimeMeasureId }>) => void;
  walk: (args: Readonly<{ whoId: WhoId; x: number; y: number }>) => void;
  useItem: (args: Readonly<{ whoId: WhoId; itemId: ItemId }>) => void;
  fixEngineRoom: () => void;
  showFirstTimeHelp: () => void;
  endCutsceneMode: () => void;
  recoil: () => void;
  explore: () => void;
  setDisguise: (args: Readonly<{ whoId: WhoId; disguide: DisguiseId }>) => void;
  createCreature: (args: Readonly<{ whoId: WhoId; x: number; y: number; direction: Direction }>) => void;
  addJournalEntry: (args: Readonly<{ journalId: JournalId; type: JournalTypeId }>) => void;
  eraseJournalEntry: (journalId: JournalId) => void;
  isInNpcArea: (args: Readonly<{ whoId: WhoId; aroundNpd: WhoId }>) => boolean;
  saveGame: (slot: number) => void;
  hideFloatMessageOver: (whoId: WhoId) => void;
  showFloatMessageOver: (args: Readonly<{ whoId: WhoId; messageId: MessageId }>) => void;
  changeDialog: (args: Readonly<{ whoId: WhoId; dialogueId: string }>) => void;
  changeAllegiance: (args: Readonly<{ whoId: WhoId; allegianceId: string }>) => boolean;
}>;
