// this file calculates entity size based on source code,
// that reads the entity from buffer

// this file is almost autogenerated:
// 1. transform reader.ts into js
// 2. remove buffer and just() calls

const numberAsBoolean = (x, sourceName = null) => {
  {
    switch (x) {
      case 0:
        return false
      case 1:
        return true
      default:
        throw new Error(
          `Property ${x} is out of boolean 0..1 range for ${sourceName ??
            "unspecified source"}`
        )
    }
  }
}

const createReader = (buffer, initialOffset = 0) => {
  let offset = initialOffset
  const skipCustom = bytes => {
    offset += bytes
  }

  //

  const byte = () => {
    offset += 1
  }
  const mapByte = (map, or = null) => byte()
  const booleanByte = (sourceName = null) => byte()
  const skipByte = () => skipCustom(1)

  //

  const ubyte = () => {
    offset += 1
  }
  const mapUbyte = (map, or = null) => ubyte()
  const booleanUbyte = (sourceName = null) => ubyte()
  const skipUbyte = () => skipCustom(1)

  //

  const short = () => {
    offset += 2
  }
  const mapShort = (map, or = null) => short()
  const booleanShort = (sourceName = null) => short()
  const skipShort = () => skipCustom(2)

  //

  const ushort = () => {
    offset += 2
  }
  const mapUshort = (map, or = null) => ushort()
  const booleanUshort = (sourceName = null) => ushort()
  const skipUshort = () => skipCustom(2)

  //

  const int = () => {
    offset += 4
  }
  const mapInt = (map, or = null) => int()
  const booleanInt = (sourceName = null) => int()
  const skipInt = () => skipCustom(4)

  //

  const uint = () => {
    offset += 4
  }
  const mapUint = (map, or = null) => uint()
  const booleanUint = (sourceName = null) => uint()
  const skipUint = () => skipCustom(4)

  //

  const string = (length, asIs = false, encoding = "ascii") => {
    offset += length
  }
  const mapString = (length, map, asIs = false, encoding = "ascii") => string(length, asIs, encoding)

  const customBytes = length => {
    for (let i = 0; i < length; i++) {
      const b = byte()
    }
  }
  const fork = (newOffset = null) => createReader(buffer, newOffset ?? offset)
  // const readLineByLine = (trim = true, toLower = true, encoding = "utf-8") => { }

  return {
    get buffer() {
      return buffer
    },
    get offset() {
      return offset
    },
    get offsetHex() {
      return `0x${offset.toString(16)}`
    },
    fork,
    customBytes,
    // readLineByLine,
    byte,
    ubyte,
    short,
    ushort,
    int,
    uint,
    string,
    map: {
      byte: mapByte,
      ubyte: mapUbyte,
      short: mapShort,
      ushort: mapUshort,
      int: mapInt,
      uint: mapUint,
      string: mapString
    },
    boolean: {
      byte: booleanByte,
      ubyte: booleanUbyte,
      short: booleanShort,
      ushort: booleanUshort,
      int: booleanInt,
      uint: booleanUint
    },
    skip: {
      byte: skipByte,
      ubyte: skipUbyte,
      short: skipShort,
      ushort: skipUshort,
      int: skipInt,
      uint: skipUint,
      custom: skipCustom
    }
  }
}
