import type { BitsPerPixel } from '../../shared/validateBitsPerPixel.types.js';
import type { Compression } from '../../shared/validateCompression.types.js';

export type RawBmpV5Header = Readonly<{
  signature: 'bm';
  version: 'v5';
  fileSize: number;
  rasterDataOffset: number;
  infoHeaderSize: number;
  width: number;
  height: number;
  topDown: boolean;
  planesCount: number;
  bitsPerPixel: BitsPerPixel;
  compression: Compression;
  horizontalResolution: number;
  verticalResolution: number;
  imageSize: number;
  usedColors: number;
  importantColors: number;
  redMask: number;
  greenMask: number;
  blueMask: number;
  alphaMask: number;
  colorSpaceType: number;
  redX: number;
  redY: number;
  redZ: number;
  greenX: number;
  greenY: number;
  greenZ: number;
  blueX: number;
  blueY: number;
  blueZ: number;
  gammaRed: number;
  gammaGreen: number;
  gammaBlue: number;
  intent: number;
  profileData: number;
  profileSize: number;
}>;
