import { allCategories } from '@/discoverer.types.js';
import createWriter from '@/shared/writer.js';
import { join } from 'path';
import { saveToFile } from '@/shared/customFs.js';

import type { Discovered } from '@/discoverer.types.js';
import type { Pathes } from '../1.createPathes/index.js';

const serialize = (name: string, items: string[]) => {
  const uppercaseName = name[0]!.toUpperCase() + name.slice(1);
  const writer = createWriter();

  writer.writeLine('/* Autogenerated file */');
  writer.br();
  writer.writeLine(`export type ${uppercaseName}Id`);
  writer.writeLine(`  = | '${items[0]!}'`);
  for (const item of items.slice(1)) writer.writeLine(`    | '${item}'`);
  writer.writeLine(';');
  return writer.done();
};

const saveDiscovered = async (discovered: Discovered, pathes: Pathes): Promise<void> => {
  for (const category of allCategories) {
    const items = discovered.get(category)!;
    const ts = serialize(category, items.sort());
    const targetFile = join(pathes.output.sharedEnums, `${category}.ts`);
    await saveToFile(targetFile, ts, true);
  }
};

export default saveDiscovered;
