import { allCategories } from '@/discoverer.types.js';
import createWriter from '@/shared/writer.js';
import { join } from 'path';
import { saveToFile } from '@/shared/customFs.js';

import type { Discovered } from '@/discoverer.types.js';
import type { Pathes } from '../1.createPathes/index.js';
import { nothing, type Maybe } from '@planar/shared';

const detectVariableType = (variable: string, spectre: Maybe<Set<string | number>>): Maybe<string> => {
  if (!spectre || spectre.size === 0) return nothing();
  const types = new Set([...spectre].map(v => typeof v));
  if (types.size > 1) {
    const x = [...types].join(', ');
    throw new Error(`Variable '${variable}' cannot exists in several types: ${x}`);
  }

  const firstType = [...types][0];
  if (firstType === 'string') {
    return 'string';
  }

  if (firstType === 'number') {
    const values = [...spectre] as number[];
    const onlyZeroOne = values.every(v => v === 0 || v === 1);
    return onlyZeroOne ? 'boolean' : 'number';
  }

  throw new Error(`Variable '${variable}' has unknown type '${firstType}'`);
};

const serializeVariables = (variables: string[], spectres: Map<string, Set<string | number>>) => {
  const numberWriter = createWriter();
  const numberEmptyStoreWriter = createWriter();
  const booleanWriter = createWriter();
  const booleanEmptyStoreWriter = createWriter();
  // const stringWriter = createWriter(); // no string are found

  numberWriter.writeLine('export type NumberVariableId');
  numberEmptyStoreWriter.writeLine('export const emptyNumberStore: Record<NumberVariableId, number> = {');
  booleanWriter.writeLine('export type BooleanVariableId');
  booleanEmptyStoreWriter.writeLine('export const emptyBooleanStore: Record<BooleanVariableId, boolean> = {');

  let foundNumberVariable = false;
  let foundBooleanVariable = false;
  for (const variable of variables) {
    const spectre = spectres.get(variable);
    if (!spectre || spectre.size === 0) {
      console.warn(`Why there is an empty spectre for variable '${variable}'?`);
    }

    const variableType = detectVariableType(variable, spectre);

    if (!foundNumberVariable && variableType === 'number') {
      foundNumberVariable = true;
      numberWriter.writeLine(`  = | '${variable}'`);
      numberEmptyStoreWriter.writeLine(`  '${variable}': 0,`);
      continue;
    }
    if (!foundBooleanVariable && variableType === 'boolean') {
      foundBooleanVariable = true;
      booleanWriter.writeLine(`  = | '${variable}'`);
      booleanEmptyStoreWriter.writeLine(`  '${variable}': false,`);
      continue;
    }

    if (variableType === 'number') {
      numberWriter.writeLine(`    | '${variable}'`);
      numberEmptyStoreWriter.writeLine(`  '${variable}': 0,`);
    }
    if (variableType === 'boolean') {
      booleanWriter.writeLine(`    | '${variable}'`);
      booleanEmptyStoreWriter.writeLine(`  '${variable}': false,`);
    }
  }

  numberWriter.writeLine(';');
  numberEmptyStoreWriter.writeLine('};');
  booleanWriter.writeLine(';');
  booleanEmptyStoreWriter.writeLine('};');

  return `/* Autogenerated file */\n\n${numberWriter.done()}\n${booleanWriter.done()}\n${numberEmptyStoreWriter.done()}\n${booleanEmptyStoreWriter.done()}`;
};

const serialize = (name: string, items: string[]) => {
  const uppercaseName = name[0]!.toUpperCase() + name.slice(1);
  const writer = createWriter();

  writer.writeLine('/* Autogenerated file */');
  writer.br();
  writer.writeLine(`export type ${uppercaseName}Id`);
  writer.writeLine(`  = | '${items[0]!}'`);
  for (const item of items.slice(1)) writer.writeLine(`    | '${item}'`);
  writer.writeLine(';');
  return writer.done();
};

const saveDiscovered = async (discovered: Discovered, pathes: Pathes): Promise<void> => {
  for (const category of allCategories) {
    const items = discovered.variables.get(category)!;
    const ts = category === 'variable' ? serializeVariables(items.sort(), discovered.spectres) : serialize(category, items.sort());
    const targetFile = join(pathes.output.sharedEnums, `${category}.ts`);
    await saveToFile(targetFile, ts, true);
  }
};

export default saveDiscovered;
